changelog:
  exclude:
    labels:
      - skip-changelog
      - internal
  categories:
    - title: Security
      labels: [security]
    - title: New capabilities
      labels: [enhancement, feature]
    - title: Fixes
      labels: [bug, fix]
    - title: Documentation and community
      labels: [documentation, community]
    - title: Dependencies
      labels: [dependencies]
    - title: Other changes
      labels: ["*"]
