import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import path from "node:path";
import test from "node:test";

const root = process.cwd();
const read = (file) => readFile(path.join(root, file), "utf8");

test("#1212 exposes one editable Human presentation and exactly three unconfigured BUZZ choices", async () => {
  const [panel, overlay, layout] = await Promise.all([
    read("app/profile-access/profile-identity-panel.tsx"),
    read("app/profile-access/profile-identity-overlay.tsx"),
    read("app/layout.tsx"),
  ]);

  assert.equal(panel.match(/<span>Display name \(agent name\)<\/span>/gu)?.length, 1);
  assert.equal(panel.match(/<span>Display Description<\/span>/gu)?.length, 1);
  assert.doesNotMatch(panel, /<span>Avatar<\/span>/u);
  assert.match(panel, /<span>Lore Avatar prompt<\/span>/u);
  assert.match(panel, /Generate Lore Avatar/u);
  assert.match(panel, /data-buzz-setup-choices="true"[\s\S]*Get BUZZ Identity[\s\S]*Connect Existing Identity[\s\S]*Not Now/u);
  assert.doesNotMatch(panel, /Create BUZZ Identity/u);
  assert.match(panel, /BUZZ_IDENTITY_ONBOARDING_URL/u);
  assert.match(panel, /BUZZ creates and owns the identity/u);
  assert.match(panel, /function ProfilePortrait/u);
  assert.match(panel, /if \(presentation\.avatarUrl\) return <img/u);
  assert.match(panel, /data-default-lore-glyph="true"/u);
  assert.match(panel, /DEFAULT_HUMAN_LORE_GLYPH/u);
  assert.match(panel, /publicBio: next\.publicBio/u);
  assert.match(panel, /BUZZ Identity[\s\S]*View identity details/u);

  assert.match(overlay, /ProfileIdentityPanel/u);
  assert.match(overlay, /plotpickle:profile-action/u);
  for (const action of ["add-profile", "lock", "switch-profile", "logout"]) assert.ok(overlay.includes(`dispatch("${action}")`), `Profile must preserve the ${action} Auth action`);
  assert.match(layout, /<ProfileAccessBoundary>\{children\}<\/ProfileAccessBoundary>[\s\S]*<ProfileIdentityOverlay \/>/u);
});

test("#1212 saves the Human Profile locally before optional BUZZ publication and keeps presentation on the canonical local Auth gateway", async () => {
  const [panel, route, localGateway] = await Promise.all([
    read("app/profile-access/profile-identity-panel.tsx"),
    read("app/api/auth/profile-presentation/route.ts"),
    read("build/local-profile-auth-gateway.ts"),
  ]);

  const saveStart = panel.indexOf("async function savePresentation");
  const saveEnd = panel.indexOf("async function finishBuzzSetup");
  const save = panel.slice(saveStart, saveEnd);
  assert.ok(saveStart >= 0 && saveEnd > saveStart);
  assert.ok(save.indexOf("/api/auth/profile-presentation") < save.indexOf("publishToBuzz(result.profile)"));
  assert.match(save, /local Profile was not rolled back/u);

  assert.match(route, /PRESENTATION_OBJECT_ID = "human-presentation"/u);
  assert.match(route, /updateProfilePresentation/u);
  assert.match(route, /writePrivateJson\(authContext, \{ domain: "settings", objectId: PRESENTATION_OBJECT_ID/u);
  assert.doesNotMatch(route, /local-buzz|BUZZ_PRIVATE_KEY|buzz-connection/u);
  assert.match(route, /localSaved: true/u);

  assert.match(localGateway, /PROFILE_PRESENTATION_API = "\/api\/auth\/profile-presentation"/u);
  assert.match(localGateway, /profilePresentationGet/u);
  assert.match(localGateway, /profilePresentationPost/u);
  assert.match(localGateway, /handlers: Object\.freeze\(\{ GET: profilePresentationGet, POST: profilePresentationPost \}\)/u);
});

test("#1277 BUZZ identity is acquired in BUZZ, imported into the active Human vault, and never generated by PlotPickle", async () => {
  const [gateway, credentials, defaults, vite] = await Promise.all([
    read("build/buzz-profile-identity-gateway.ts"),
    read("build/local-credentials.ts"),
    read("lib/buzz/buzz-default-community.ts"),
    read("vite.config.ts"),
  ]);

  assert.doesNotMatch(gateway, /createECDH|generateKeys\(|generatedPrivateKey/u);
  assert.match(gateway, /action === "create"[\s\S]*PlotPickle does not create BUZZ identities/u);
  assert.match(gateway, /action === "import"/u);
  assert.match(gateway, /action === "disconnect"/u);
  assert.match(gateway, /action === "publish-profile"/u);
  assert.doesNotMatch(gateway, /recoveryPrivateKey/u);
  assert.match(gateway, /identityPubkey: verification\.pubkey/u);
  assert.match(gateway, /identityRole: "human"/u);
  assert.match(gateway, /connection\.identityPubkey = verification\.pubkey/u);
  assert.match(gateway, /connection\.identityRole = "human"/u);
  assert.match(gateway, /boundHuman\(connection, pubkey\)/u);
  assert.match(gateway, /A PlotPickle agent BUZZ identity cannot be connected as the Human Profile/u);
  assert.match(gateway, /"users", "set-profile", "--name", displayName, "--about", bio/u);
  assert.match(gateway, /args\.push\("--avatar", picture\)/u);
  assert.match(gateway, /BUZZ_PRIVATE_KEY: connection\.privateKey/u);
  assert.doesNotMatch(gateway, /--private-key|--nsec/u);
  assert.match(gateway, /writeCredentialJson\(CONNECTION_FILE/u);

  assert.match(defaults, /BUZZ_IDENTITY_ONBOARDING_URL = "https:\/\/github\.com\/block\/buzz\/releases\/latest"/u);
  assert.match(defaults, /displayName: "PlotPickle Playhouse"/u);
  assert.match(defaults, /requiredConnection: true/u);
  assert.match(defaults, /removableByHuman: false/u);
  assert.match(defaults, /allowHumanOwnedCommunities: true/u);
  assert.match(defaults, /memberRequirement: "plotpickle-human-with-connected-buzz"/u);
  assert.match(defaults, /socialAuthority: "buzz"/u);

  assert.match(credentials, /PROFILE_SCOPED_BUZZ_CREDENTIAL = "buzz-connection\.json"/u);
  assert.match(credentials, /privateStorage\.readCredential\(profileContext\.authContext, safeName\)/u);
  assert.match(credentials, /privateStorage\.writeCredential\(profileContext\.authContext, safeName, value\)/u);

  const context = vite.indexOf("profileScopedBuzzRequestContext()");
  const profileIdentity = vite.indexOf("buzzProfileIdentityGateway()");
  const humanGuard = vite.indexOf("buzzHumanIdentityGuard()");
  assert.ok(context >= 0 && profileIdentity > context && humanGuard > profileIdentity, "the authenticated Human scope must wrap BUZZ identity mutation and Community verification");
});

test("#1277 bound Human signer authority survives mutable BUZZ presentation while legacy Agent detection stays fail-closed", async () => {
  const [gateway, guard] = await Promise.all([
    read("build/buzz-profile-identity-gateway.ts"),
    read("build/buzz-human-identity-guard.ts"),
  ]);

  assert.match(gateway, /connection\.identityRole === "human"/u);
  assert.match(gateway, /connection\.identityPubkey\.toLowerCase\(\) === pubkey\.toLowerCase\(\)/u);
  assert.match(gateway, /const agentId = boundHuman\(connection, pubkey\) \? "" : agentIdForDisplayName\(displayName\)/u);
  assert.match(guard, /const roleBoundHuman = connection\.identityRole === "human" && boundPubkey === localPubkey/u);
  assert.match(guard, /const agent = roleBoundHuman \? null : agentForDisplayName\(displayName\)/u);
  assert.match(guard, /saved Human BUZZ role binding does not match the stored signer/u);
  assert.match(guard, /kind: "agent"/u);
  assert.match(guard, /humanCommunityAllowed: false/u);
});
