import assert from "node:assert/strict";
import test from "node:test";
import {authorizeNode,claimOrAdoptAvatar,createAccountSyncState,createPortableLearnState} from "../core/identity/account-learn-sync-core.mjs";
import {createIosAgentRequest,createIosCommunityCatalog,createIosCompanionIdentity,createIosLearnProjection,projectIosBuzzEvent} from "../core/mobile/ios-companion-core.mjs";

function account(){let value=createAccountSyncState("person-bryan");value=authorizeNode(value,{nodeId:"node-home",publicKeyPem:"-----BEGIN PUBLIC KEY-----\nIOS\n-----END PUBLIC KEY-----",authorizedAt:"2026-08-19T18:00:00.000Z"});return claimOrAdoptAvatar(value,"node-home",{draftId:"draft-ios",displayName:"Bryan"},{avatarId:"avatar-bryan",now:"2026-08-19T18:01:00.000Z"}).account}
function communities(){return[{id:"scriptorium",name:"The Scriptorium",purpose:"Writing and story work",agents:[{agentId:"sage",displayName:"Sage",role:"Lorekeeper",allowedCapabilities:["learn-help"]}],remoteExecutionAllowed:true},{id:"atelier",name:"The Atelier",purpose:"Visual development",agents:[{agentId:"marquee",displayName:"Marquee",role:"Visual director",minimumCurriculumStage:"foundations-complete",allowedCapabilities:["visual-review"]}],remoteExecutionAllowed:true},{id:"workshop",name:"The Workshop",purpose:"Production-oriented work",agents:[{agentId:"avery",displayName:"Avery",role:"Writer in residence",allowedCapabilities:["production-review"]}],remoteExecutionAllowed:true},{id:"engine-room",name:"The Engine Room",purpose:"Technical support",agents:[{agentId:"ben",displayName:"BEN",role:"Verification agent",allowedCapabilities:["status-report"]}],remoteExecutionAllowed:true},{id:"great-hall",name:"The Great Hall",purpose:"Human social community",agents:[{agentId:"merrin-bellwarden",displayName:"Merrin Bellwarden",role:"Moderator",allowedCapabilities:["moderation"]}],remoteExecutionAllowed:false}]}

test("iOS uses the canonical account Avatar and portable LEARN only",()=>{const a=account();assert.equal(createIosCompanionIdentity(a).avatar.avatarId,"avatar-bryan");const learn=createPortableLearnState({activeLessonId:"lesson-1",activeLessonUpdatedAt:"2026-08-19T18:02:00.000Z",completedLessonIds:[],bookmarks:{},notes:[],curriculumAnswers:[],sageMessages:[],lessonVersions:{},visualWriterFrontier:null});const mobile=createIosLearnProjection(a,learn);assert.equal(mobile.authority,"portable-learn-sync");assert.equal(mobile.ppfIncluded,false);assert.equal(mobile.buildControlsIncluded,false);assert.equal(mobile.nodeControlsIncluded,false)});

test("first iOS architecture has exactly five communities and Great Hall is human-only",()=>{const catalog=createIosCommunityCatalog({communities:communities()});assert.equal(catalog.communities.length,5);assert.equal(catalog.communities.find(c=>c.communityId==="great-hall").humanOnly,true);assert.throws(()=>createIosCommunityCatalog({communities:communities().slice(0,4)}),/exactly five/i);const invalid=communities();invalid[4].agents.push({agentId:"sage",displayName:"Sage",role:"Lorekeeper",allowedCapabilities:[]});assert.throws(()=>createIosCommunityCatalog({communities:invalid}),/Merrin moderation only/i)});

test("iOS consumes signed BUZZ events but events are not permission grants",()=>{const event=projectIosBuzzEvent({eventId:"event-1",type:"agent_response",communityId:"scriptorium",roomId:"room-story",avatarId:"avatar-bryan",content:"A bounded response",createdAt:"2026-08-19T18:03:00.000Z",signatureVerified:true});assert.equal(event.permissionGrant,false);assert.throws(()=>projectIosBuzzEvent({...event,eventId:"event-2",signatureVerified:false}),/signature-verified/i)});

test("mobile agent requests remain host-authorized and cannot directly execute shell MCP or provider operations",()=>{const request=createIosAgentRequest({requestId:"request-1",communityId:"engine-room",roomId:"room-status",agentId:"ben",capability:"status-report",message:"What is the latest verification status?"});assert.equal(request.requiresHostAuthorization,true);for(const forbidden of [{arbitraryShell:true},{rawMcp:true},{providerOperation:true}])assert.throws(()=>createIosAgentRequest({requestId:"request-2",communityId:"engine-room",roomId:"room-status",agentId:"ben",capability:"status-report",message:"Run it",...forbidden}),/cannot directly execute/i)});
