import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { stripTypeScriptTypes } from "node:module";
import test from "node:test";

const root = new URL("../", import.meta.url);
const source = (path) => readFile(new URL(path, root), "utf8");

async function inspectionModule() {
  const typeScript = await source("lib/preproduction/provider-instruction-inspection.ts");
  const compiled = stripTypeScriptTypes(typeScript, { mode: "transform" });
  return import(`data:text/javascript;base64,${Buffer.from(compiled).toString("base64")}#provider-instruction-inspection-${Date.now()}-${Math.random()}`);
}

function bundle(strategy = "per-shot") {
  return {
    version: 1,
    disposable: true,
    providerId: "openai",
    capability: "video",
    strategy,
    projectId: "story-2064",
    canonicalRevision: 24,
    directionLevel: "production",
    instructions: strategy === "master"
      ? [{ id: "instruction-master", scope: "master", text: "MASTER INSTRUCTION", sourceRefs: ["scene-1"] }]
      : [
          {
            id: "instruction-shot-1",
            scope: "shot",
            editorialShotId: "editorial-shot-1",
            productionShotId: "production-shot-1",
            text: "SHOT ONE INSTRUCTION",
            sourceRefs: ["scene-1", "production-shot-1"],
          },
          {
            id: "instruction-shot-2",
            scope: "shot",
            editorialShotId: "editorial-shot-2",
            productionShotId: "production-shot-2",
            text: "SHOT TWO INSTRUCTION",
            sourceRefs: ["scene-1", "production-shot-2"],
          },
        ],
    finishingRequirements: [{
      property: "delivery.frame-rate",
      strength: "required",
      sourceRef: "delivery:fps",
      treatment: "finishing",
      note: "Normalize frame rate in finishing/export.",
      userVisibleAdaptationRequired: false,
    }],
    unsupportedPreferences: [{
      property: "audio",
      strength: "preferred",
      sourceRef: "audio:scene-1",
      treatment: "unsupported",
      note: "Audio is not generated by this route.",
      userVisibleAdaptationRequired: false,
    }],
    warnings: ["Shot timing is best-effort for this provider."],
    sourceRefs: ["story-2064:story", "scene-1"],
  };
}

test("#2064 Phase 4 projects generated provider instructions as disposable non-canonical read-only inspection", async () => {
  const { inspectProviderInstructionBundle } = await inspectionModule();
  const inspection = inspectProviderInstructionBundle(bundle(), {
    editorialShotId: "editorial-shot-2",
    productionShotId: "production-shot-2",
  });

  assert.equal(inspection.version, 1);
  assert.equal(inspection.disposable, true);
  assert.equal(inspection.canonical, false);
  assert.equal(inspection.editable, false);
  assert.equal(inspection.providerId, "openai");
  assert.equal(inspection.strategy, "per-shot");
  assert.equal(inspection.canonicalRevision, 24);
  assert.equal(inspection.directionLevel, "production");
  assert.equal(inspection.instructions.length, 1);
  assert.equal(inspection.instructions[0].editorialShotId, "editorial-shot-2");
  assert.equal(inspection.instructions[0].text, "SHOT TWO INSTRUCTION");
  assert.equal(inspection.finishingRequirements[0].property, "delivery.frame-rate");
  assert.equal(inspection.unsupportedPreferences[0].property, "audio");
  assert.deepEqual(inspection.warnings, ["Shot timing is best-effort for this provider."]);
});

test("#2064 Phase 4 keeps master instructions scene-wide and fails closed on invalid disposable output", async () => {
  const { inspectProviderInstructionBundle } = await inspectionModule();
  const master = inspectProviderInstructionBundle(bundle("master"), {
    editorialShotId: "editorial-shot-2",
  });
  assert.equal(master.instructions.length, 1);
  assert.equal(master.instructions[0].scope, "master");

  assert.throws(() => inspectProviderInstructionBundle({ ...bundle(), disposable: false }), /disposable output only/i);
  assert.throws(() => inspectProviderInstructionBundle({ ...bundle(), instructions: [] }), /at least one generated instruction/i);
});

test("#2064 Phase 4 exposes the existing Visual Story advanced inspection seam without adding prompt persistence or editing", async () => {
  const [inspection, visualStory, readiness] = await Promise.all([
    source("lib/preproduction/provider-instruction-inspection.ts"),
    source("app/_components/storyboard/visual-story-workspace.tsx"),
    source("app/_components/storyboard/storyboard-readiness-workspace.tsx"),
  ]);

  assert.match(inspection, /disposable: true/);
  assert.match(inspection, /canonical: false/);
  assert.match(inspection, /editable: false/);
  assert.doesNotMatch(inspection, /fetch\(|localStorage|sessionStorage|saveFoundationProject|writeFile|media-routing|story-mode-policy/);

  assert.match(visualStory, /ProviderInstructionBundle/);
  assert.match(visualStory, /inspectProviderInstructionBundle/);
  assert.match(visualStory, /View generated director instructions/);
  assert.match(visualStory, /Disposable provider output — not Story \/ PPF \/ canon/);
  assert.match(visualStory, /data-provider-instruction-inspection="read-only"/);
  assert.match(visualStory, /<pre[^>]*>\{instruction\.text\}<\/pre>/);
  assert.match(visualStory, /Capability warnings/);
  assert.match(visualStory, /Finishing \/ post requirements/);
  assert.doesNotMatch(visualStory, /persistPrompt|savePrompt|writePrompt|canonicalPrompt/);

  assert.match(readiness, /providerInstructions\?: ProviderInstructionBundle \| null/);
  assert.match(readiness, /providerInstructions=\{providerInstructions\}/);
});

test("#2064 Phase 4 remains inspection-only and leaves provider selection and execution for the existing routing boundary", async () => {
  const combined = [
    await source("lib/preproduction/provider-instruction-inspection.ts"),
    await source("app/_components/storyboard/visual-story-workspace.tsx"),
    await source("app/_components/storyboard/storyboard-readiness-workspace.tsx"),
  ].join("\n");

  assert.doesNotMatch(combined, /selectProvider|routeProvider|writeRoutingChoice|selectRoute|generateOpenAiVideo|submitWorkflow|providerJson|providerForm/);
  assert.doesNotMatch(combined, /Seedance|Runway|Veo|Kling/);
});
