import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { createProfileUserProject, initializeProfileProjectLibrary, listProfileProjectSummaries, switchProfileActiveProject } from "../core/storage/project-library-core.mjs";

class MemoryStorage { #values = new Map(); get length() { return this.#values.size; } key(index) { return [...this.#values.keys()][index] ?? null; } getItem(key) { return this.#values.has(key) ? this.#values.get(key) : null; } setItem(key, value) { this.#values.set(String(key), String(value)); } removeItem(key) { this.#values.delete(key); } }
const NOW = "2026-08-22T03:50:00.000Z";
function normalizeProject(value) { if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error("invalid project"); return { id:String(value.id||"project"), title:String(value.title||"Untitled Story"), revision:Number.isInteger(value.revision)?value.revision:0, createdAt:String(value.createdAt||NOW), updatedAt:String(value.updatedAt||NOW), learning:value.learning||{activeLessonId:null,completedLessonIds:[]}, foundations:value.foundations||{activeLessonId:null,lessons:{},brief:{content:"",savedAt:null}}, world:value.world||{activeLessonId:null,lessons:{},brief:{content:"",savedAt:null}}, build:value.build||{foundations:{visualArtifacts:[],acceptedVisualArtifactIds:[]},world:{visualArtifacts:[],acceptedVisualArtifactIds:[]}}, creativeRoom:value.creativeRoom||{threadId:null} }; }
function createProject({id,now,title}) { return normalizeProject({id,title,createdAt:now,updatedAt:now}); }
function harness(storage) { const ids=["human-active","generated-foundations"]; return { storage, profileId:"profile-human", normalizeProject, createProject, describeProject:()=>({progress:0,frontier:"Foundations",thumbnail:""}), now:()=>NOW, idFactory:()=>ids.shift()||"fallback-story" }; }

test("#1253 canonical Library user-project creation saves the active Human story and gives the generated story a new id", () => { const storage=new MemoryStorage(); const input=harness(storage); const initial=initializeProfileProjectLibrary(input); assert.equal(initial.activeProject.id,"human-active"); const generated=createProfileUserProject({...input,title:"The New Story",genre:"Mystery",format:"Story"}); assert.equal(generated.activeProject.id,"generated-foundations"); assert.notEqual(generated.activeProject.id,initial.activeProject.id); assert.deepEqual(listProfileProjectSummaries(input).map((item)=>item.id),["generated-foundations","human-active"]); const restored=switchProfileActiveProject({...input,projectId:"human-active"}); assert.equal(restored.activeProject.id,"human-active","the pre-auto-complete Human story remains reopenable"); });

test("#1253 Writer-in-Residence history is owned by Library rather than Dashboard", async () => { const [dashboard,library,history]=await Promise.all([readFile(new URL("../modules/dashboard/ui/dashboard-workspace.tsx",import.meta.url),"utf8"),readFile(new URL("../modules/library/ui/library-workspace.tsx",import.meta.url),"utf8"),readFile(new URL("../modules/library/ui/avery-session-history/index.tsx",import.meta.url),"utf8")]); assert.doesNotMatch(dashboard,/AverySessionHistory/u); assert.match(library,/AverySessionHistory/u); assert.match(history,/searchParams\.set\("workspace", "library"\)/u); assert.match(history,/Back to Library/u); assert.match(history,/Exactly four Library positions stay reserved/u); assert.doesNotMatch(history,/Back to Dashboard|Dashboard positions stay reserved/u); });

test("#1253 Auto-complete creates an original isolated story and completes all Foundations contracts", async () => { const [autoStory,workspace,browserStore,builderSource]=await Promise.all([readFile(new URL("../modules/plan/foundations-auto-story.ts",import.meta.url),"utf8"),readFile(new URL("../modules/plan/ui/foundations-plan-workspace.tsx",import.meta.url),"utf8"),readFile(new URL("../core/storage/project-library-browser.ts",import.meta.url),"utf8"),readFile(new URL("../modules/learn/full-story-builder.mjs",import.meta.url),"utf8")]); assert.match(autoStory,/normalizeFullStoryBrief/u); assert.match(autoStory,/createLibraryUserProject/u); assert.match(autoStory,/for \(const \[index, lesson\] of input\.lessons\.entries\(\)\)/u); assert.match(autoStory,/type: "foundations\.proposal\.accept"/u); assert.match(autoStory,/type: "lesson\.complete"/u); assert.match(autoStory,/saveFoundationProject\(workingProject\)/u); assert.match(autoStory,/assembleFoundationsBrief/u); assert.match(autoStory,/type: "foundations\.brief\.save"/u); assert.match(autoStory,/originalitySeed/u); assert.match(browserStore,/createLibraryUserProject/u); assert.match(builderSource,/normalizeFullStoryBrief/u); assert.match(workspace,/Create a new story and auto-complete Foundations/u); assert.match(workspace,/Your previous story is never overwritten/u); assert.match(workspace,/autoCompleteNewFoundationsStory/u); assert.match(workspace,/result\.project\.id === previousProjectId/u); assert.match(workspace,/Create & auto-complete Foundations/u); assert.doesNotMatch(workspace,/disabled=\{!ppfSource[^}]*autoCompletingFoundations/u); assert.match(workspace,/loading a \.ppf only supplies read-only evidence/u); });
