"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import styles from "./verification-inbox.module.css";

type Summary={runId:string;headline:string;deterministicResult:"PASS"|"FAIL";passCount:number;totalStages:number;plotPickleVersion:string;git:{commit:string;ref:string};startedAt:string;completedAt:string;platformClass:string};
type Stage={number:number;name:string;category:string;status:"PASS"|"FAIL"|"BLOCKED";exitCode:number;detail:string};
type Observation={agent?:string;severity?:string;summary?:string};
type AgentReview={summary?:string;participants?:Array<{label?:string;participated?:boolean;authority?:string}>;agentObservations?:Observation[];likelyProductDefects?:string[];likelyHarnessDefects?:string[];originalDeterministicResult?:string};
type Repair={status?:string;worker?:string;summary?:string;requiresRerun?:boolean;originalRunId?:string};
type Record=Summary&{stages:Stage[];categoryResults:Array<{category:string;status:string}>;evidenceReferences:Array<{kind:string;ref:string}>;agentObservations:Observation[];failureSummaries:Array<{stage:string;status:string;summary:string}>;repairAttempts:Repair[];retests:Summary[];agentReview?:AgentReview|null;integrity:{deterministicResultDerivedFromStages:boolean;agentMayOverrideResult:boolean}};
const date=(value:string)=>{const parsed=new Date(value);return Number.isNaN(parsed.getTime())?"Not recorded":parsed.toLocaleString();};
const commit=(value:string)=>value?value.slice(0,12):"not available";

export default function VerificationInboxPage(){
  const[runs,setRuns]=useState<Summary[]>([]);const[selected,setSelected]=useState("");const[record,setRecord]=useState<Record|null>(null);const[notice,setNotice]=useState("Loading verification history…");
  async function refresh(){const response=await fetch("/api/verification-inbox");const body=await response.json() as{records?:Summary[];message?:string};if(!response.ok)throw new Error(body.message||"Verification Inbox could not be loaded.");const next=body.records||[];setRuns(next);setNotice(next.length?"":"No Full Verification runs have been recorded yet.");if(next.length&&!selected)setSelected(next[0].runId);}
  useEffect(()=>{void refresh().catch((error)=>setNotice(error instanceof Error?error.message:"Verification Inbox could not be loaded."));},[]);
  useEffect(()=>{if(!selected)return;setRecord(null);void fetch(`/api/verification-inbox?runId=${encodeURIComponent(selected)}`).then(async(response)=>{const body=await response.json() as{record?:Record;message?:string};if(!response.ok||!body.record)throw new Error(body.message||"That run could not be loaded.");setRecord(body.record);}).catch((error)=>setNotice(error instanceof Error?error.message:"That run could not be loaded."));},[selected]);
  return <main className={styles.page}>
    <header className={styles.hero}><div><p>Quality / Verification Inbox</p><h1>Every Full Verification run, kept as evidence.</h1><span>Local application records only — never story canon. Deterministic PASS/FAIL comes from the nine verification stages and cannot be changed by an agent.</span></div><div><button onClick={()=>void refresh()}>Refresh</button><Link href="/?workspace=reports">Back to Reports</Link></div></header>
    <div className={styles.layout}>
      <aside className={styles.runs} aria-label="Recent Full Verification runs"><header><strong>Recent runs</strong><small>{runs.length} stored locally</small></header>{runs.map(run=><button key={run.runId} aria-current={selected===run.runId?"true":undefined} data-result={run.deterministicResult} onClick={()=>setSelected(run.runId)}><span><b>{run.passCount}/{run.totalStages} {run.deterministicResult}</b><small>{date(run.completedAt||run.startedAt)}</small></span><em>{commit(run.git.commit)}</em></button>)}{!runs.length?<p>Run <code>Run-PlotPickle-Full-Check.bat</code> to create the first record.</p>:null}</aside>
      <section className={styles.detail} aria-live="polite">{record?<>
        <header className={styles.result} data-result={record.deterministicResult}><span>{record.deterministicResult==="PASS"?"Verification complete":"Needs attention"}</span><h2>{record.headline}</h2><p>PlotPickle {record.plotPickleVersion} · commit {commit(record.git.commit)} · {record.git.ref||"ref unavailable"}</p></header>
        <div className={styles.meta}><span><b>Started</b>{date(record.startedAt)}</span><span><b>Completed</b>{date(record.completedAt)}</span><span><b>Platform</b>{record.platformClass}</span><span><b>Integrity</b>{record.integrity.deterministicResultDerivedFromStages&&!record.integrity.agentMayOverrideResult?"Deterministic":"Needs attention"}</span></div>
        <section><h3>Nine-stage verification</h3><div className={styles.stages}>{record.stages.map(stage=><article key={stage.number} data-status={stage.status}><i>{stage.number}</i><div><strong>{stage.name.replace(/^\d+ of 9 - /,"")}</strong><small>{stage.category}</small>{stage.detail?<p>{stage.detail}</p>:null}</div><b>{stage.status}</b></article>)}</div></section>
        <section className={styles.review}><h3>Review</h3>{record.failureSummaries.length?record.failureSummaries.map(item=><article key={item.stage}><strong>{item.status} · {item.stage}</strong><p>{item.summary}</p></article>):<p className={styles.clean}>No findings were invented for this clean run. All nine deterministic stages passed.</p>}
          {record.agentReview?<article><strong>Agent review — advisory only</strong><p>{record.agentReview.summary||"No advisory summary was recorded."}</p><small>{(record.agentReview.participants||[]).filter(item=>item.participated).map(item=>`${item.label} (${item.authority})`).join(" · ")||"No agent participation was recorded."}</small></article>:<p>No separate agent review was recorded.</p>}
          {record.agentObservations.length?<>{record.agentObservations.slice(0,6).map((item,index)=><article key={`${item.agent||"agent"}-${index}`}><strong>{item.agent||"Agent"} · {item.severity||"advisory"}</strong><p>{item.summary||"Observation recorded."}</p></article>)}</>:<p>No separate agent observations were recorded.</p>}
          {record.repairAttempts.length?record.repairAttempts.map((item,index)=><article key={`repair-${index}`}><strong>Repair attempt · {item.worker||"Pi"} · {item.status||"recorded"}</strong><p>{item.summary||"Bounded repair evidence recorded."}</p>{item.requiresRerun?<small>A new deterministic Full Verification rerun is required before PASS/FAIL can change.</small>:null}</article>):<p>No repair attempts were recorded.</p>}
          {record.retests.length?record.retests.map(item=><article key={item.runId}><strong>Linked retest · {item.deterministicResult} · {item.passCount}/{item.totalStages}</strong><p>{item.headline} · commit {commit(item.git?.commit||"")}</p></article>):<p>No linked retests were recorded.</p>}
        </section>
        <details className={styles.technical}><summary>Technical details and evidence</summary><p><b>Run ID</b> <code>{record.runId}</code></p><p><b>Commit</b> <code>{record.git.commit||"Not available"}</code></p><h4>Category results</h4><ul>{record.categoryResults.map(item=><li key={item.category}>{item.category}: <b>{item.status}</b></li>)}</ul><h4>Evidence references</h4>{record.evidenceReferences.length?<ul>{record.evidenceReferences.map((item,index)=><li key={index}><b>{item.kind}</b>: <code>{item.ref}</code></li>)}</ul>:<p>No separate evidence references were recorded.</p>}<h4>Stage exit codes</h4><ul>{record.stages.map(stage=><li key={stage.number}>{stage.number}. {stage.status} · exit {stage.exitCode}</li>)}</ul></details>
      </>:<div className={styles.placeholder}><h2>{notice||"Choose a verification run."}</h2><p>The raw transcript remains separate; its structured summary appears here.</p></div>}</section>
    </div>{notice&&record?<p className={styles.notice}>{notice}</p>:null}
  </main>;
}
