"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { FOUNDATION_PROJECT_STORAGE_KEY } from "../core/contracts/foundation-plan";
import { normalizeFoundationProject, type PPFProject } from "../core/project/project";
import { BUZZ_GUILDHALL_ACTORS, BUZZ_GUILDHALL_CHANNELS } from "../lib/buzz-guildhall";
import { BUZZ_STORY_ROOMS, buzzProjectSlug, buzzRoomName, type BuzzStoryRoomId } from "../lib/buzz-story-room";
import CommunityAgentRoster from "./community-agent-roster";
import CommunityNavigationRail, { type CommunitySection } from "./community-navigation-rail";
import navigationStyles from "./community-navigation-rail.module.css";
import CommunityStoryRoomAccess from "./community-story-room-access";
import styles from "./community-workspace.module.css";

const BUZZ_API = "/api/local-buzz";
const PROPOSAL_STORAGE_KEY = "plotpickle.buzz.proposals.v1";
type BuzzChannel = { id: string; name: string; description: string };
type CommunityMember = { pubkey: string; displayName: string; presence: string; updatedAt: string };
type ActivityItem = { id: string; content: string; author: string; createdAt: string };
type CommunityStatus = { configured: boolean; identityVerified: boolean; community: string; relayUrl: string; identityLabel: string; greatHall: BuzzChannel | null; members: CommunityMember[]; recentActivity: ActivityItem[]; canManageGreatHall: boolean; fullRosterSupported: boolean; inviteManagement: "buzz-desktop"; message: string };
type GuildhallStatus = { configured: boolean; identityVerified: boolean; canSetup: boolean; operational: boolean; readyCount: number; totalCount: number; readyRooms: Array<{ id: string; name: string; label: string; channelId: string }>; missingRooms: Array<{ id: string; name: string; label: string }>; message: string };
type StoryRoomRecord = { roomId: BuzzStoryRoomId; channel: BuzzChannel; created?: boolean };
type BuzzMessage = { id: string; content: string; author: string; createdAt: string };
type ReviewItem = { id: string; title: string; status: string; roomId?: string; createdAt?: string };

async function request<T>(path: string, init?: RequestInit): Promise<T> {
  const response = await fetch(`${BUZZ_API}${path}`, { ...init, headers: { Accept: "application/json", "Content-Type": "application/json", ...(init?.headers ?? {}) } });
  const body = await response.json() as T & { message?: string };
  if (!response.ok) throw new Error(body.message || `Buzz returned ${response.status}.`);
  return body;
}
function readProject(): PPFProject | null { if (typeof window === "undefined") return null; const source = window.localStorage.getItem(FOUNDATION_PROJECT_STORAGE_KEY); if (!source) return null; try { return normalizeFoundationProject(JSON.parse(source)); } catch { return null; } }
function readReviews(): ReviewItem[] { if (typeof window === "undefined") return []; try { const source = window.localStorage.getItem(PROPOSAL_STORAGE_KEY); const value: unknown = source ? JSON.parse(source) : []; if (!Array.isArray(value)) return []; return value.flatMap((entry) => { if (!entry || typeof entry !== "object" || Array.isArray(entry)) return []; const item = entry as Record<string, unknown>; if (item.status !== "open") return []; return [{ id: typeof item.id === "string" ? item.id : crypto.randomUUID(), title: typeof item.title === "string" && item.title ? item.title : "Community story suggestion", status: "open", roomId: typeof item.roomId === "string" ? item.roomId : undefined, createdAt: typeof item.createdAt === "string" ? item.createdAt : undefined }]; }); } catch { return []; } }
function displayDate(value?: string) { if (!value) return "Recently"; const date = new Date(value); return Number.isNaN(date.getTime()) ? "Recently" : date.toLocaleString(); }
function buzzDesktopUrl(relay: string, name: string) { try { const url = new URL(relay); if (!["ws:", "wss:"].includes(url.protocol)) return ""; const query = new URLSearchParams({ relay: url.toString().replace(/\/$/, "") }); if (name.trim()) query.set("name", name.trim()); return `buzz://add-community?${query.toString()}`; } catch { return ""; } }

export default function CommunityWorkspace({ onOpenSettings }: { readonly onOpenSettings: () => void }) {
  const [section, setSection] = useState<CommunitySection>("overview");
  const [community, setCommunity] = useState<CommunityStatus | null>(null);
  const [guildhall, setGuildhall] = useState<GuildhallStatus | null>(null);
  const [project, setProject] = useState<PPFProject | null>(null);
  const [storyRooms, setStoryRooms] = useState<StoryRoomRecord[]>([]);
  const [selectedRoomId, setSelectedRoomId] = useState<BuzzStoryRoomId>("story");
  const [selectedGuildhallRoomId, setSelectedGuildhallRoomId] = useState("");
  const [storyMessages, setStoryMessages] = useState<BuzzMessage[]>([]);
  const [hallDraft, setHallDraft] = useState("");
  const [storyDraft, setStoryDraft] = useState("");
  const [memberPubkey, setMemberPubkey] = useState("");
  const [memberRole, setMemberRole] = useState("member");
  const [reviews, setReviews] = useState<ReviewItem[]>([]);
  const [busy, setBusy] = useState("");
  const [notice, setNotice] = useState("");
  const hallComposerRef = useRef<HTMLTextAreaElement>(null);

  const selectedRoom = storyRooms.find((room) => room.roomId === selectedRoomId) ?? null;
  const selectedGuildhallDefinition = BUZZ_GUILDHALL_CHANNELS.find((room) => room.id === selectedGuildhallRoomId) ?? null;
  const selectedGuildhallRuntime = guildhall?.readyRooms.find((room) => room.id === selectedGuildhallRoomId) ?? null;
  const onlineMembers = community?.members.filter((member) => member.presence === "online").length ?? 0;
  const activeProjectName = project?.title || "No active story";
  const storyPrefix = useMemo(() => project ? buzzProjectSlug(project) : "", [project]);
  const desktopUrl = buzzDesktopUrl(community?.relayUrl || "", community?.community || "");

  async function refreshCommunity(showNotice = false) {
    const [communityBody, guildhallBody] = await Promise.all([request<CommunityStatus & { ok: true }>("/community/status"), request<GuildhallStatus & { ok: true }>("/guildhall/status")]);
    setCommunity(communityBody); setGuildhall(guildhallBody);
    if (!selectedGuildhallRoomId) setSelectedGuildhallRoomId(guildhallBody.readyRooms.find((room) => room.id !== "great-hall")?.id || "");
    if (showNotice) setNotice(communityBody.message);
    return { communityBody, guildhallBody };
  }
  async function loadStoryMessages(room = selectedRoom) { if (!room) { setStoryMessages([]); return; } const body = await request<{ messages: BuzzMessage[] }>(`/messages?channel=${encodeURIComponent(room.channel.id)}&limit=40`); setStoryMessages(body.messages); }
  useEffect(() => { setProject(readProject()); setReviews(readReviews()); let cancelled = false; void refreshCommunity(false).then(({ communityBody }) => { if (cancelled || !communityBody.identityVerified) return; const current = readProject(); if (!current) return; const prefix = buzzProjectSlug(current); return request<{ rooms: BuzzChannel[] }>(`/rooms?projectPrefix=${encodeURIComponent(prefix)}`).then((body) => { if (cancelled) return; const mapped = body.rooms.flatMap((channel) => { const definition = BUZZ_STORY_ROOMS.find((room) => channel.name === buzzRoomName(current, room.id)); return definition ? [{ roomId: definition.id, channel } satisfies StoryRoomRecord] : []; }); setStoryRooms(mapped); if (mapped.length) setSelectedRoomId(mapped[0].roomId); }); }).catch((error) => { if (!cancelled) setNotice(error instanceof Error ? error.message : "Community status could not be loaded."); }); return () => { cancelled = true; }; }, []);
  async function run(name: string, operation: () => Promise<void>) { setBusy(name); setNotice(""); try { await operation(); } catch (error) { setNotice(error instanceof Error ? error.message : "The Community action could not be completed."); } finally { setBusy(""); } }
  async function setupGuildhall() { await run("guildhall", async () => { const result = await request<GuildhallStatus & { message: string }>("/guildhall/setup", { method: "POST" }); setGuildhall(result); if (!selectedGuildhallRoomId) setSelectedGuildhallRoomId(result.readyRooms.find((room) => room.id !== "great-hall")?.id || ""); setNotice(result.message); }); }
  async function ensureStoryRooms() { if (!project) { setNotice("Open LEARN or PLAN once so PlotPickle has an active story before creating Story Rooms."); return; } await run("story-rooms", async () => { const body = await request<{ rooms: StoryRoomRecord[] }>("/rooms/ensure", { method: "POST", body: JSON.stringify({ projectPrefix: buzzProjectSlug(project), rooms: BUZZ_STORY_ROOMS.map((room) => ({ id: room.id, name: buzzRoomName(project, room.id), description: `${project.title} · ${room.description}` })) }) }); setStoryRooms(body.rooms); if (body.rooms.length) setSelectedRoomId(body.rooms[0].roomId); setNotice(`All ${body.rooms.length} private Story Rooms are ready for ${project.title}.`); }); }
  async function sendHallMessage() { if (!community?.greatHall || !hallDraft.trim()) return; await run("hall-send", async () => { await request("/messages", { method: "POST", body: JSON.stringify({ channel: community.greatHall?.id, content: hallDraft.trim() }) }); setHallDraft(""); await refreshCommunity(false); setNotice("Your signed message was added to the Great Hall."); }); }
  async function sendStoryMessage() { if (!selectedRoom || !storyDraft.trim()) return; await run("story-send", async () => { await request("/messages", { method: "POST", body: JSON.stringify({ channel: selectedRoom.channel.id, content: storyDraft.trim() }) }); setStoryDraft(""); await loadStoryMessages(selectedRoom); setNotice(`Your signed message was added to ${BUZZ_STORY_ROOMS.find((room) => room.id === selectedRoom.roomId)?.label || "the Story Room"}.`); }); }
  async function addMember() { if (!memberPubkey.trim()) return; await run("member-add", async () => { const body = await request<CommunityStatus & { ok: true }>("/community/members", { method: "POST", body: JSON.stringify({ pubkey: memberPubkey.trim(), role: memberRole }) }); setCommunity(body); setMemberPubkey(""); setNotice("The existing Buzz member was added to the PlotPickle Great Hall."); }); }
  async function removeMember(pubkey: string) { await run(`remove-${pubkey}`, async () => { const body = await request<CommunityStatus & { ok: true }>("/community/members", { method: "DELETE", body: JSON.stringify({ pubkey }) }); setCommunity(body); setNotice("Great Hall access was removed for that member."); }); }
  function openStoryRoom(roomId: BuzzStoryRoomId) { setSelectedRoomId(roomId); setSection("story-rooms"); const room = storyRooms.find((item) => item.roomId === roomId) ?? null; void loadStoryMessages(room).catch((error) => setNotice(error instanceof Error ? error.message : "Story Room messages could not be loaded.")); }
  function onOpenGuildhallRoom(roomId: string) { setSelectedGuildhallRoomId(roomId); setSection("guildhall"); setNotice(`Opened Guildhall room: ${BUZZ_GUILDHALL_CHANNELS.find((room) => room.id === roomId)?.label || roomId}.`); }
  function replyToHallMessage(item: ActivityItem) { const mention = `@${item.author || "Guild member"} `; setHallDraft((value) => value.trim() ? `${value}\n${mention}` : mention); setNotice(`Replying to ${item.author || "Guild member"}. Your reply will be posted publicly in the Great Hall.`); window.setTimeout(() => hallComposerRef.current?.focus(), 0); }

  const connected = Boolean(community?.identityVerified && community.greatHall);
  return <div className={styles.page}>
    <header className={styles.hero}><div><p>Community</p><h1>The PlotPickle Playhouse gathers here.</h1><span>People, Story Rooms and approved agents share one native PlotPickle workspace. Buzz provides the signed community layer underneath; the writer stays inside PlotPickle for normal collaboration.</span></div><div className={styles.connection} data-ready={connected ? "true" : "false"} role="status"><i aria-hidden="true" /><div><strong>{connected ? "Community connected" : "Community setup needed"}</strong><small>{community?.message || "Checking Buzz and the PlotPickle Guildhall…"}</small></div></div></header>

    <div className={navigationStyles.communityBody}>
      <CommunityNavigationRail section={section} storyRooms={storyRooms} selectedStoryRoomId={selectedRoomId} guildhallReadyRooms={guildhall?.readyRooms ?? []} selectedGuildhallRoomId={selectedGuildhallRoomId} onSectionChange={setSection} onOpenStoryRoom={openStoryRoom} onOpenGuildhallRoom={onOpenGuildhallRoom} />
      <div className={navigationStyles.communityMain}>
        {!community?.identityVerified ? <section className={styles.setupCard}><div><span>Connect once</span><h2>Community uses your locally encrypted Buzz identity.</h2><p>Open basic Settings, connect and verify your Buzz community, then return here. The private identity stays on this computer and is not stored in GitHub or the PPF.</p></div><button type="button" onClick={onOpenSettings}>Open Settings</button></section> : !guildhall?.operational ? <section className={styles.setupCard}><div><span>One-time Guildhall setup</span><h2>{guildhall ? `${guildhall.readyCount}/${guildhall.totalCount} Guildhall rooms ready` : "Prepare the PlotPickle Guildhall"}</h2><p>PlotPickle creates only the missing private rooms, then verifies them before reporting the community as operational.</p></div><button type="button" disabled={busy === "guildhall" || !guildhall?.canSetup} onClick={() => void setupGuildhall()}>{busy === "guildhall" ? "Building Guildhall…" : "Set up PlotPickle Guildhall"}</button></section> : null}

        {section === "overview" ? <main className={styles.stack}>
          <section className={styles.panel}><header><div><span>Human conversation</span><h2>Great Hall</h2></div><button type="button" onClick={() => setSection("great-hall")}>Open Great Hall</button></header><p>{community?.members.length ?? 0} members · {onlineMembers} online. Start with people and conversation; operational telemetry stays secondary.</p><div className={styles.activityList}>{community?.recentActivity.length ? community.recentActivity.slice(0, 5).map((item) => <article key={item.id}><div><strong>{item.author || "Guild member"}</strong><small>{displayDate(item.createdAt)}</small></div><p>{item.content}</p></article>) : <p className={styles.empty}>No Great Hall messages yet.</p>}</div></section>
          <section className={styles.twoColumn}><article className={styles.panel}><span>Story Rooms</span><h2>{activeProjectName}</h2><p>{storyRooms.length}/6 accessible rooms are available from the Community navigation.</p><button type="button" onClick={() => setSection("story-rooms")}>Open Story Rooms</button></article><article className={styles.panel}><span>Agents & Stewards</span><h2>{BUZZ_GUILDHALL_ACTORS.length} lore identities</h2><p>System and agent coordination remains available without crowding the human conversation surface.</p><button type="button" onClick={() => setSection("agents")}>Meet the Guildhall</button></article></section>
          <p className={styles.empty}>Nothing changes PPF canon without approval.</p>
        </main> : null}

        {section === "great-hall" ? <main className={styles.stack}><section className={styles.sectionHeading}><div><span>The Great Hall</span><h2>Public conversation for the Playhouse.</h2><p>Read, reply and post here. Story-specific discussion belongs in private Story Rooms.</p></div><button type="button" onClick={() => void refreshCommunity(true)}>Refresh Hall</button></section><section className={styles.conversation}><div className={styles.messageList}>{community?.recentActivity.length ? community.recentActivity.map((item) => <article key={item.id}><header><strong>{item.author || "Guild member"}</strong><small>{displayDate(item.createdAt)}</small></header><p>{item.content}</p><button data-community-reply-action type="button" onClick={() => replyToHallMessage(item)}>Reply to {item.author || "Guild member"}</button></article>) : <p className={styles.empty}>The Great Hall is quiet.</p>}</div><div className={styles.composer}><textarea ref={hallComposerRef} value={hallDraft} onChange={(event) => setHallDraft(event.target.value)} placeholder="Write to the Great Hall…" rows={4} /><button type="button" disabled={!connected || !hallDraft.trim() || Boolean(busy)} onClick={() => void sendHallMessage()}>{busy === "hall-send" ? "Sending…" : "Send signed message"}</button></div></section></main> : null}

        {section === "story-rooms" ? <main className={styles.stack}><section className={styles.sectionHeading}><div><span>Story Rooms</span><h2>{project ? `Private rooms for ${project.title}` : "Open a story to create its rooms"}</h2><p>Only rooms returned by your authenticated Buzz membership appear in Community navigation.</p></div><button type="button" disabled={!community?.identityVerified || !project || Boolean(busy)} onClick={() => void ensureStoryRooms()}>{busy === "story-rooms" ? "Creating…" : storyRooms.length === 6 ? "Story Rooms ready" : "Create missing Story Rooms"}</button></section>{selectedRoom ? <section className={styles.conversation}><header className={styles.roomConversationHeader}><div><span>Active room</span><h3>{BUZZ_STORY_ROOMS.find((room) => room.id === selectedRoom.roomId)?.label}</h3></div><button type="button" onClick={() => void loadStoryMessages(selectedRoom)}>Load messages</button></header><div className={styles.messageList}>{storyMessages.length ? storyMessages.map((message) => <article key={message.id}><header><strong>{message.author || "Story Room member"}</strong><small>{displayDate(message.createdAt)}</small></header><p>{message.content}</p></article>) : <p className={styles.empty}>Load this room to see its signed conversation.</p>}</div><div className={styles.composer}><textarea value={storyDraft} onChange={(event) => setStoryDraft(event.target.value)} placeholder="Discuss this story without changing canon…" rows={4} /><button type="button" disabled={!storyDraft.trim() || Boolean(busy)} onClick={() => void sendStoryMessage()}>{busy === "story-send" ? "Sending…" : "Send to Story Room"}</button></div><CommunityStoryRoomAccess channel={selectedRoom.channel} greatHallMembers={community?.members ?? []} desktopUrl={desktopUrl} /></section> : <p className={styles.empty}>Choose an accessible Story Room from Community navigation, or create the missing rooms for the active story.</p>}</main> : null}

        {section === "people" ? <main className={styles.stack}><section className={styles.sectionHeading}><div><span>People</span><h2>Great Hall members and presence</h2><p>Full community-wide invitation issuance is not exposed by the current Buzz CLI. PlotPickle shows the supported membership truth here.</p></div></section><section className={styles.memberGrid}>{community?.members.length ? community.members.map((member) => <article key={member.pubkey}><header><div><i data-presence={member.presence} aria-hidden="true" /><strong>{member.displayName}</strong></div><span>{member.presence || "offline"}</span></header><small>{member.pubkey.slice(0, 12)}…{member.pubkey.slice(-8)}</small><button type="button" disabled={Boolean(busy)} onClick={() => void removeMember(member.pubkey)}>Remove from Great Hall</button></article>) : <p className={styles.empty}>No Great Hall members were returned yet.</p>}</section><section className={styles.accessCard}><div><span>Add existing Buzz member</span><h3>Grant Great Hall access</h3></div><div className={styles.accessControls}><input value={memberPubkey} onChange={(event) => setMemberPubkey(event.target.value)} placeholder="64-character Buzz public key" /><select value={memberRole} onChange={(event) => setMemberRole(event.target.value)}><option value="member">Member</option><option value="guest">Guest</option><option value="admin">Admin</option><option value="bot">Bot</option></select><button type="button" disabled={!community?.canManageGreatHall || !memberPubkey.trim() || Boolean(busy)} onClick={() => void addMember()}>Add to Great Hall</button></div></section><section className={styles.boundaryCard}><div><span>Invite a new person</span><h3>Buzz still owns new-community invitations.</h3><p>Until Buzz exposes invitation issuance through its supported CLI/API, use Buzz Desktop for the initial invite; after they join, PlotPickle can manage their Great Hall and Story Room access here.</p></div>{desktopUrl ? <a href={desktopUrl}>Open community in Buzz Desktop</a> : <button type="button" onClick={onOpenSettings}>Finish Buzz setup</button>}</section></main> : null}

        {section === "agents" ? <main className={styles.stack}><CommunityAgentRoster /></main> : null}
        {section === "reviews" ? <main className={styles.stack}><section className={styles.sectionHeading}><div><span>Review Queue</span><h2>Community discussion never becomes canon by itself.</h2><p>Selected discussion can become a proposal, but the writer must explicitly approve a change before the PPF is updated.</p></div></section><section className={styles.reviewList}>{reviews.length ? reviews.map((review) => <article key={review.id}><div><strong>{review.title}</strong><small>{review.roomId ? `From ${review.roomId}` : "Community proposal"} · {displayDate(review.createdAt)}</small></div><span>Awaiting human review</span></article>) : <p className={styles.empty}>Nothing is waiting for review.</p>}</section></main> : null}

        {section === "guildhall" ? <main className={styles.stack}><section className={styles.sectionHeading}><div><span>Guildhall</span><h2>Internal coordination underneath the Playhouse</h2><p>Choose an available room from the Guildhall expansion in Community navigation instead of scanning an operational card wall.</p></div><button type="button" disabled={!guildhall?.canSetup || guildhall?.operational || Boolean(busy)} onClick={() => void setupGuildhall()}>{guildhall?.operational ? "Guildhall operational" : "Create missing rooms"}</button></section>{selectedGuildhallDefinition && selectedGuildhallRuntime ? <article className={styles.panel} data-guildhall-room-detail data-guildhall-room-id={selectedGuildhallRoomId}><span>Available Guildhall room</span><h2>{selectedGuildhallDefinition.label}</h2><p>{selectedGuildhallDefinition.description}</p><small>Internal coordination · {selectedGuildhallRuntime.name}</small></article> : <p className={styles.empty}>Expand Guildhall in Community navigation and choose an available internal room.</p>}</main> : null}

        {notice ? <p className={styles.notice} role="status">{notice}</p> : null}
      </div>
    </div>
  </div>;
}
