import type { LearningModule } from "./learning-library";

export type DialogueLesson = LearningModule & {
  collection: "Dialogue in Motion";
  sourceAliases: string[];
  sourceNote: string;
  workspaceLabel: string;
  workspaceHref: string;
  workspaceSection: string;
  focus: "action" | "voice" | "subtext" | "conflict" | "silence" | "exposition" | "exchange" | "revision";
};

export const dialogueLegacySourceMap = [
  { source: "Different Genres", lessonId: "dialogue-exposition-genre" },
  { source: "Conflict", lessonId: "dialogue-conflict" },
  { source: "Balancing Action", lessonId: "dialogue-speech-silence-action" },
  { source: "Distinctive Voices", lessonId: "dialogue-voiceprint" },
  { source: "Realistic Dialogue", lessonId: "dialogue-action" },
  { source: "Dialogue Pitfalls", lessonId: "dialogue-revision" },
  { source: "Tags and Beats", lessonId: "dialogue-speech-silence-action" },
  { source: "Subtext", lessonId: "dialogue-subtext" },
  { source: "Reveal Character", lessonId: "dialogue-voiceprint" },
  { source: "Refining Dialogue", lessonId: "dialogue-revision" },
  { source: "Art of Silence", lessonId: "dialogue-speech-silence-action" },
] as const;

export const dialoguePurposeLabels = ["pressure", "evade", "reveal", "conceal", "test", "persuade", "threaten", "bond", "deflect", "explain", "joke", "surrender", "change topic", "silence/reaction"] as const;

export const dialogueBlueprintFields = [
  "participants",
  "relationship state",
  "each objective",
  "each tactic",
  "public topic",
  "private subject",
  "information imbalance",
  "status at entry",
  "intended turn",
  "exit condition",
  "required continuity facts",
  "locked lines or facts",
] as const;

export const dialogueGuidedPasses = [
  { id: "critique-only", label: "Critique only", instruction: "Diagnose purpose, objective, voice, subtext, status, action and scene movement. Do not rewrite." },
  { id: "voice-separation", label: "Voice separation", instruction: "Compare rhythm, vocabulary, directness, metaphor, humour, emotional access and persuasion. Preserve deliberate shared language." },
  { id: "objective-tactic", label: "Objective and tactic", instruction: "Clarify what each participant wants, the tactic used, resistance and the tactic change." },
  { id: "subtext", label: "Subtext", instruction: "Strengthen the gap between public topic, actual objective, protected fact and cost of direct speech without making every line cryptic." },
  { id: "status-leverage", label: "Status and leverage", instruction: "Track status at entry, leverage changes, exposure, options and the resulting turn." },
  { id: "conflict-escalation", label: "Conflict escalation", instruction: "Escalate through changed conditions, cost, information, relationship or available options rather than volume alone." },
  { id: "exposition-reduction", label: "Exposition reduction", instruction: "Keep only information needed now and attach it to conflict, task, urgency, misunderstanding or consequence." },
  { id: "action-silence", label: "Action and silence alternatives", instruction: "Find visible behaviour, reaction, interruption, task, distance, entrance or exit that can carry meaning without explanatory speech." },
  { id: "rhythm-concision", label: "Rhythm and concision", instruction: "Improve exchange rhythm, interruption, breath, readability and performance while preserving purposeful release or repetition." },
  { id: "genre-expectation", label: "Genre expectation", instruction: "Support the intended audience experience through pressure and information control without imposing a genre stereotype." },
  { id: "continuity-arc", label: "Continuity and arc consistency", instruction: "Check facts, relationship state, Voiceprint tendencies and arc evidence while allowing motivated variation under pressure." },
  { id: "compare-approaches", label: "Compare two approaches", instruction: "Offer two materially different playable strategies, explain tradeoffs and keep the original separate." },
] as const;

export function dialogueQuestionsForContext(context: {
  blockNumber: number;
  miniBlockNumber: number;
  characterName?: string;
  relationshipLabel?: string;
  sceneObjective?: string;
  sceneOpposition?: string;
  sceneTurn?: string;
  genre?: string;
  worldRules?: string;
}) {
  return [
    `What does each speaker want before Block ${context.blockNumber}.${context.miniBlockNumber} begins?`,
    `Which tactic fails in this ${context.sceneObjective ? `scene objective: ${context.sceneObjective}` : "exchange"}, and what replaces it?`,
    `Where does leverage, information or understanding change${context.sceneTurn ? ` before the planned turn: ${context.sceneTurn}` : ""}?`,
    `Does ${context.characterName || "the selected character"}'s voice vary because of relationship, status, stress, intimacy, deception or growth rather than random inconsistency?`,
    `How does the current relationship${context.relationshipLabel ? ` (${context.relationshipLabel})` : ""} change what may be said directly?`,
    `Does the exchange serve the Block goal, conflict, choice or consequence rather than repeat an earlier strategy?`,
    `Could visible action, image, sound, interruption or silence carry part of the information better?`,
    `Does the ${context.genre || "genre"} pressure shape timing and audience expectation without dictating one dialogue style?`,
    context.worldRules ? `Are world terms understood through objective and consequence under these rules: ${context.worldRules}?` : "Are unfamiliar terms understood through objective and consequence?",
    context.sceneOpposition ? `How is the scene opposition (${context.sceneOpposition}) audible or playable without constant argument?` : "What resistance prevents immediate agreement or direct speech?",
  ];
}

const sourceNote = "PlotPickled from eleven legacy Dialogue resources into one screenplay-specific system. Original titles remain searchable while dialogue is taught as playable speech, silence and action under pressure.";
function lesson(input: Omit<DialogueLesson, "collection" | "sourceNote" | "workspaceLabel" | "workspaceHref">): DialogueLesson {
  return { ...input, collection: "Dialogue in Motion", sourceNote, workspaceLabel: "Dialogue in Motion workspace", workspaceHref: "/dialogue-in-motion" };
}

export const dialogueLessons: DialogueLesson[] = [
  lesson({ id: "dialogue-action", number: 61, path: "Craft", title: "Dialogue Is Action", duration: "25–35 min", overview: "Treat every exchange as behaviour: speech, silence and physical action used to pursue an objective under pressure.", objectives: ["Map objectives, tactics and resistance.", "Track information and leverage.", "End with a changed condition."], sections: [{ heading: "The playable exchange", paragraphs: ["A line is not merely information. It may pressure, evade, seduce, test, accuse, bargain, distract, conceal, provoke, reassure, recruit, threaten, surrender or change the subject.", "Begin with relationship condition, each objective, each belief about the other, tactic, resistance, information held or withheld, status, spoken action, physical action, turn and changed exit condition."], points: dialoguePurposeLabels.map((item) => `Possible spoken or silent action: ${item}`) }, { heading: "Selected reality", paragraphs: ["Realistic dialogue is selected reality. Literal conversation contains filler, repetition and dead space; screenplay naturalism shapes truthful behaviour for purpose, rhythm and performance.", "Not every line must advance plot. A line may reveal relationship, regulate pace, establish tone, create anticipation, release pressure or make later action meaningful."] }], definitions: [{ term: "Tactic", meaning: "The playable strategy used to pursue an immediate objective." }, { term: "Exit condition", meaning: "What is materially different when the exchange ends." }], example: { title: "The request that becomes a test", text: "A character asks for a ride, but the actual objective is to test whether an estranged sibling will show up. A delayed answer changes the relationship before either discusses it directly." }, checklist: ["Each participant wants something now.", "Resistance is active.", "A tactic changes.", "The exit differs from the entry."], mistakes: ["Using dialogue only to transfer facts.", "Polishing isolated lines before designing the exchange.", "Equating realism with transcription."], exercise: "Create a Dialogue Blueprint for the active scene or mini-block and label the first tactic, resistance and turn.", apply: "Screenplay", tags: ["Realistic Dialogue", "natural dialogue", "dialogue action", "objective", "tactic", "turn"], sourceAliases: ["Realistic Dialogue"], workspaceSection: "blueprint", focus: "action" }),
  lesson({ id: "dialogue-voiceprint", number: 62, path: "Craft", title: "Build a Playable Voiceprint", duration: "30–40 min", overview: "Connect Voiceprint tendencies to perception, rhythm, vocabulary, emotional access, status and persuasion without reducing voice to accent or catchphrase.", objectives: ["Turn character fields into playable tendencies.", "Compare voices with evidence.", "Allow motivated variation."], sections: [{ heading: "Voice is perception plus strategy", paragraphs: ["Voice is what a character notices, how they organize thought and how they try to affect another person. Use sentence rhythm, vocabulary and metaphor families, directness, humour and defence, emotional access, silence patterns, persuasion and status behaviour.", "A believable voice changes with audience, power, fear, intimacy, deception, exhaustion and growth. Consistency does not mean sameness."], points: ["Origin and environment", "Social context", "Education and expertise", "Worldview boundaries", "Rhythm and sentence shape", "Vocabulary and metaphors", "Verbal fingerprints", "Emotional access", "Status shifts", "Persuasion strategy"] }, { heading: "Accent and dialect require care", paragraphs: ["Do not use phonetic spelling or demographic shorthand as a substitute for character. Prioritize researched syntax, vocabulary, rhythm, worldview and context, and seek informed human review where appropriate.", "AI may surface comparison questions but cannot certify cultural authenticity or imitate a real performer without permission."] }], definitions: [{ term: "Voiceprint", meaning: "A flexible pattern of perception, language and strategy supported by screenplay evidence." }], example: { title: "Shared profession, different tactic", text: "Two surgeons share technical vocabulary. One compresses language to control status; the other uses precise questions to slow decisions and expose risk." }, checklist: ["Tendencies are playable.", "Relationship variation is motivated.", "Shared language is allowed.", "Dialect is researched."], mistakes: ["Treating accent as voice.", "Flagging every variation as inconsistency.", "Repeating catchphrases mechanically."], exercise: "Compare two active characters across rhythm, directness, metaphor, emotional access, status and persuasion, then find supporting lines.", apply: "Screenplay", tags: ["Distinctive Voices", "Reveal Character", "Voiceprint", "accent", "dialect", "verbal fingerprints"], sourceAliases: ["Distinctive Voices", "Reveal Character"], workspaceSection: "voice", focus: "voice" }),
  lesson({ id: "dialogue-subtext", number: 63, path: "Craft", title: "Write Subtext and Withheld Information", duration: "25–35 min", overview: "Create subtext from objectives, relationships, protected facts and the cost of direct speech rather than cryptic wording.", objectives: ["Separate spoken and private subjects.", "Track audience knowledge and interpretation.", "Design reveal or misread turns."], sections: [{ heading: "The pressure system", paragraphs: ["Map the spoken subject, actual objective, hidden feeling or belief, protected fact, audience knowledge, the other character's interpretation, cost of direct speech, indirect tactic and reveal, misread or turn.", "Use irony, avoidance, deflection, euphemism, implication, denial, testing, strategic misunderstanding and behaviour that contradicts the words. Not every line needs hidden meaning."], points: ["Public topic", "Private subject", "Protected fact", "Cost of direct speech", "Indirect tactic", "Other character's interpretation", "Audience knowledge", "Reveal or misread"] }], definitions: [{ term: "Subtext", meaning: "Meaning created by the gap among words, objective, feeling, knowledge and behaviour." }], example: { title: "Talking about the thermostat", text: "A couple debates room temperature while testing who still expects to share the house. Moving a suitcase becomes the actual answer." }, checklist: ["A direct statement has a cost.", "The indirect tactic is purposeful.", "The audience can track enough meaning.", "Behaviour contributes."], mistakes: ["Making every line obscure.", "Adding vague pauses instead of playable evidence.", "Confusing withheld information with arbitrary concealment."], exercise: "Write the public topic and private subject for the active exchange, then identify one protected fact and one visible contradiction.", apply: "Screenplay", tags: ["Subtext", "on-the-nose", "withheld information", "irony", "deflection"], sourceAliases: ["Subtext"], workspaceSection: "blueprint", focus: "subtext" }),
  lesson({ id: "dialogue-conflict", number: 64, path: "Craft", title: "Create Conflict Without Constant Arguments", duration: "25–35 min", overview: "Build dialogue conflict from incompatible objectives, unequal knowledge, status, affection, delay, refusal and changing tactics.", objectives: ["Broaden conflict beyond shouting.", "Escalate by changing conditions.", "Use relationship cost."], sections: [{ heading: "Conflict can be polite", paragraphs: ["Agreement may conceal conflict; politeness may be a weapon; silence may be refusal; affection may increase the cost of disagreement. Use incompatible objectives, competing interpretations, unequal information, moral disagreement, negotiation, lies, half-truths, refusal, delay and changing tactics.", "Escalation should alter leverage, cost, exposure, time, relationship or available options, not only volume."] }], definitions: [{ term: "Leverage", meaning: "Information, status, access, need or consequence that changes available choices." }], example: { title: "The friendly interview", text: "A detective remains courteous while narrowing the witness's options. The escalation is a revealed photograph, not louder speech." }, checklist: ["Objectives conflict.", "Leverage changes.", "Affection or status affects tactics.", "Escalation changes conditions."], mistakes: ["Making every conflict an argument.", "Repeating the same tactic louder.", "Using hostility where strategic agreement is stronger."], exercise: "Identify the active exchange's incompatible objectives and design one escalation that changes options rather than volume.", apply: "Block plan", tags: ["Conflict", "dialogue conflict", "status", "leverage", "negotiation", "half-truth"], sourceAliases: ["Conflict"], workspaceSection: "blueprint", focus: "conflict" }),
  lesson({ id: "dialogue-speech-silence-action", number: 65, path: "Craft", title: "Balance Speech, Silence and Physical Action", duration: "25–35 min", overview: "Use visible behaviour, reactions, tasks, interruption, distance and silence as parts of the exchange and teach accurate screenplay form.", objectives: ["Replace unnecessary speech with action.", "Make silence playable.", "Use screenplay elements correctly."], sections: [{ heading: "The answer may be physical", paragraphs: ["Action can change a line's meaning or replace it. Silence may be refusal, processing, control, fear, intimacy, judgement or uncertainty. Props, tasks, entrances, exits, distance, interruptions, overlap and unfinished thoughts can carry pressure.", "Avoid abstract instructions such as an awkward silence when a withheld action, changed distance or delayed answer can make the event playable."] }, { heading: "Screenplay form", paragraphs: ["Character cues identify the speaker. Dialogue contains spoken text. Action lines carry visible behaviour. Parentheticals are brief and necessary. Extensions clarify off-screen or voice-over delivery when needed. Dual dialogue indicates simultaneous speech. Prose tags such as he said or she asked are generally not screenplay dialogue formatting.", "Write a pause only when the dramatic event matters, not as routine performance control."] }], definitions: [{ term: "Character cue", meaning: "The screenplay element identifying who speaks." }, { term: "Parenthetical", meaning: "A brief, necessary performance or delivery clarification." }, { term: "Dual dialogue", meaning: "Two speeches formatted to occur simultaneously." }], example: { title: "The unsigned form", text: "Instead of saying I don't trust you, the character caps the pen and slides the form back." }, checklist: ["Action changes meaning.", "Silence has a playable cause.", "Parentheticals are necessary.", "No prose dialogue tags."], mistakes: ["Writing he said in screenplay dialogue.", "Using parentheticals for every emotion.", "Calling silence awkward without evidence."], exercise: "Replace one explanatory line with a visible reaction or task, then verify character cue, action, parenthetical and dialogue formatting.", apply: "Screenplay", tags: ["Balancing Action", "Tags and Beats", "Art of Silence", "dialogue tags", "action beats", "parenthetical", "dual dialogue"], sourceAliases: ["Balancing Action", "Tags and Beats", "Art of Silence"], workspaceSection: "table-read", focus: "silence" }),
  lesson({ id: "dialogue-exposition-genre", number: 66, path: "Craft", title: "Handle Exposition, World and Genre", duration: "30–40 min", overview: "Attach needed information to conflict, task, urgency and relationship while using genre as pressure rather than a voice stereotype.", objectives: ["Determine what is needed now.", "Reveal rules through use and consequence.", "Avoid genre stereotypes."], sections: [{ heading: "Information under pressure", paragraphs: ["Identify what the audience must know now, who wants it understood, hidden, distorted or acted upon, and whether both characters already know it. Attach information to conflict, task, urgency, misunderstanding or consequence.", "Reveal world rules through use and consequence. Repeat crucial information through changed meaning rather than identical explanation."] }, { heading: "Genre affects pressure", paragraphs: ["Comedy may use rhythm, reversal, status and consequence; horror denial, incomplete knowledge, dread and silence; thriller concealment, interrogation, clocks and unstable alliances; romance desire, vulnerability, avoidance and changing intimacy; speculative stories unfamiliar terms with clear human objectives.", "Genre does not dictate one dialogue style. Comedy is not always banter, drama need not be formal and science fiction does not require jargon."] }], definitions: [{ term: "Exposition", meaning: "Information the audience needs to understand story conditions, choices or consequences." }, { term: "Exposition dump", meaning: "A concentration of information detached from active dramatic need." }], example: { title: "A rule revealed by failure", text: "Instead of explaining the city's memory tax, a character attempts a purchase and loses access to a sibling's name." }, checklist: ["Information is needed now.", "Knowledge imbalance is credible.", "World terms have consequence.", "Genre pressure avoids cliché."], mistakes: ["Characters explaining shared facts.", "Using jargon instead of objective.", "Making every comedy line witty."], exercise: "Find one explanatory exchange and attach its essential information to an objective, task or consequence.", apply: "Screenplay", tags: ["Different Genres", "exposition dump", "world terms", "genre dialogue", "jargon"], sourceAliases: ["Different Genres"], workspaceSection: "proof", focus: "exposition" }),
  lesson({ id: "dialogue-exchange-turn", number: 67, path: "Craft", title: "Shape the Exchange and Scene Turn", duration: "25–35 min", overview: "Design complete dialogue movements—entry tension, tactic, resistance, tactic change, reveal, status shift, irreversible action, turn and exit consequence.", objectives: ["Plan the movement.", "Handle group patterns.", "Link to scene and Story Thread turns."], sections: [{ heading: "Movement before polish", paragraphs: ["Plan the entry question or tension, first tactic, response and resistance, tactic change, reveal or misinterpretation, status shift, irreversible line or action, turn and exit question or consequence.", "Two-person, ensemble, interrogation, argument, confession, negotiation, seduction, comic, remote, overlapping and one-sided conversations are patterns, not formulas."] }], definitions: [{ term: "Exchange turn", meaning: "The point where leverage, understanding, commitment or relationship condition changes." }], example: { title: "Group agreement that isolates one person", text: "A planning meeting appears cooperative until each practical concession removes the protagonist's authority." }, checklist: ["Entry tension clear.", "Tactic changes.", "Status shifts.", "Exit creates consequence."], mistakes: ["Polishing lines without a turn.", "Giving every participant the same understanding.", "Ending when the facts are delivered."], exercise: "Map the active scene from entry tension to exit consequence and mark the irreversible line or action.", apply: "Block plan", tags: ["scene turn", "interrogation", "confession", "negotiation", "overlap", "ensemble dialogue"], sourceAliases: ["Conflict", "Realistic Dialogue"], workspaceSection: "blueprint", focus: "exchange" }),
  lesson({ id: "dialogue-revision", number: 68, path: "Drafting", title: "Revise for Voice, Purpose and Performance", duration: "35–45 min", overview: "Diagnose the exchange before rewriting, then use focused passes for purpose, tactic, voice, subtext, exposition, status, action, rhythm, continuity and performance.", objectives: ["Run bounded passes.", "Use evidence-based diagnostics.", "Preserve original and approval controls."], sections: [{ heading: "Twelve focused passes", paragraphs: ["Review purpose and movement; objective and tactic; voice separation; subtext; exposition and repetition; status and escalation; action and silence; rhythm and breath; concision; continuity, arc and relationship; formatting and production clarity; read-aloud response.", "A diagnostic question is not a universal failure rule. A long speech, repeated phrase, dialogue-heavy scene or shared vocabulary may be deliberate and effective."] }, { heading: "Manual and optional AI workflows", paragraphs: ["Writers can perform every pass manually. AI suggestions must be optional, bounded and reviewable. Preserve the original, proposed version, explanation, affected continuity, provenance and explicit approve/discard controls.", "Synthetic voices must remain optional and must not imitate a real performer without permission."] , points: dialogueGuidedPasses.map((item) => `${item.label}: ${item.instruction}`) }], definitions: [{ term: "Dialogue pass", meaning: "A focused diagnostic or revision operation with a defined craft goal." }, { term: "Table read", meaning: "A performance-oriented reading used to test clarity, rhythm, intention and response." }], example: { title: "Diagnose before cutting", text: "A repeated line appears redundant until the table read shows that its third use reverses status and completes a motif." }, checklist: ["Problem diagnosed.", "Pass bounded.", "Original preserved.", "Evidence compared.", "Writer approves explicitly."], mistakes: ["Cutting every line that does not advance plot.", "Applying AI output automatically.", "Treating diagnostic counts as grades."], exercise: "Run one guided pass on the selected exchange, read it aloud and record what changed in objective, tactic, rhythm or performance.", apply: "Screenplay", tags: ["Dialogue Pitfalls", "Refining Dialogue", "read aloud", "table read", "dialogue diagnostics", "approval"], sourceAliases: ["Dialogue Pitfalls", "Refining Dialogue"], workspaceSection: "diagnostics", focus: "revision" }),
];

export function dialogueLessonSearchText(module: DialogueLesson) {
  return [module.collection, module.sourceAliases.join(" "), module.sourceNote, module.focus, dialogueLegacySourceMap.map((item) => item.source).join(" "), dialoguePurposeLabels.join(" "), dialogueBlueprintFields.join(" "), dialogueGuidedPasses.map((item) => `${item.label} ${item.instruction}`).join(" "), "natural dialogue dialogue conflict distinctive voices on-the-nose exposition dump dialogue tags action beats subtext silence read aloud refining dialogue character cues extensions dual dialogue"].join(" ").toLowerCase();
}
