import type { LearningModule } from "./learning-library";

export type StoryCraftLesson = LearningModule & {
  collection: "Story Craft Essentials";
  sourceAliases: string[];
  sourceNote: string;
  workspaceLabel: string;
  workspaceHref: string;
  workspaceSection: string;
  focus: "experience" | "pacing" | "tone" | "theme" | "scene" | "evidence" | "motif" | "formatting" | "audit";
};

export const essentialsLegacySourceMap = [
  { source: "Storytelling Dynamics", lessonIds: ["essentials-pacing", "essentials-tone"] },
  { source: "Thematic Components", lessonIds: ["essentials-theme", "essentials-motif"] },
  { source: "Essential Aspects 1", lessonIds: ["essentials-experience", "essentials-pacing", "essentials-scene"] },
  { source: "Scene Writing", lessonIds: ["essentials-scene", "essentials-screen-evidence"] },
  { source: "Symbolic Techniques", lessonIds: ["essentials-motif", "essentials-theme"] },
  { source: "Beyond Sluglines", lessonIds: ["essentials-formatting"] },
  { source: "Essential Aspects 2", lessonIds: ["essentials-theme", "essentials-audit"] },
] as const;

export const storyCraftAuditSteps = [
  "Story promise and audience experience",
  "Causality and structure",
  "Character objective and agency",
  "Opposition, pressure and stakes",
  "Scene purpose, pivot and handoff",
  "Theme and competing answers",
  "Pacing and tonal movement",
  "Visual and sonic evidence",
  "Motifs, setups and payoffs",
  "Dialogue and Voiceprint",
  "Genre fulfilment and variation",
  "Formatting and readability",
  "Continuity and production implications",
  "Revision priorities",
] as const;

export const essentialTechniqueLibrary = [
  { id: "anticipation", label: "Anticipation", effect: "Makes the audience project forward toward an expected event or answer.", evidence: "A promised event, clock, preparation, withheld result or repeated signal.", failure: "The promise does not change, escalate or pay off.", workspace: "Structure, Story Clock and screenplay" },
  { id: "suspense", label: "Suspense", effect: "Sustains uncertainty about outcome while the audience understands meaningful risk.", evidence: "Goal, obstacle, consequence, limited time or unequal knowledge.", failure: "Risk is vague or no choice changes the outcome.", workspace: "Scene Pulse and DraftLens" },
  { id: "surprise", label: "Surprise", effect: "Reframes what the audience believed through a credible new event or fact.", evidence: "Hidden setup, changed interpretation or unexpected consequence.", failure: "The event is random or impossible to infer afterward.", workspace: "Story Threads and Resonance" },
  { id: "dramatic-irony", label: "Dramatic irony", effect: "Creates tension when the audience and character hold different knowledge.", evidence: "A visible secret, mistaken belief or delayed discovery.", failure: "The knowledge gap produces no decision or consequence.", workspace: "Dialogue, scenes and Story Threads" },
  { id: "contrast", label: "Contrast", effect: "Sharpens meaning by placing different values, rhythms, images or outcomes near one another.", evidence: "Changed scale, tone, behaviour, location, sound or consequence.", failure: "Difference exists only as decoration.", workspace: "PageFlow, storyboard and Sonic Bible" },
  { id: "repetition-variation", label: "Repetition with variation", effect: "Builds recognition and meaning through a repeated element that changes.", evidence: "A line, action, object, location, image or sound used under new conditions.", failure: "The repetition adds no new pressure or interpretation.", workspace: "Resonance and motif ledger" },
  { id: "compression-expansion", label: "Compression and expansion", effect: "Controls how much screen time an event receives relative to its dramatic importance.", evidence: "Montage, ellipsis, sustained reaction, extended process or compressed transition.", failure: "Duration does not match audience need.", workspace: "Story Clock and screenplay formatting" },
  { id: "reveal-reversal", label: "Reveal and reversal", effect: "Changes understanding or direction through information, refusal, discovery or consequence.", evidence: "A tactic fails, a fact changes meaning or a choice closes an option.", failure: "The reveal explains without changing action.", workspace: "Scene Pulse and Structure" },
  { id: "setup-payoff-reflection", label: "Setup, payoff and reflection", effect: "Creates causal and emotional satisfaction across distance.", evidence: "Introduced possibility, later consequence and audience/character interpretation.", failure: "The payoff is unearned or the setup never matters.", workspace: "Ledger and DraftLens" },
  { id: "visual-sonic-rhyme", label: "Visual and sonic rhyme", effect: "Links moments through repeated image, movement, sound or music with changed meaning.", evidence: "Opening/closing echoes, recurring sound, matched action or transformed composition.", failure: "The pattern is private, arbitrary or too literal.", workspace: "Resonance, storyboard and Sonic Bible" },
  { id: "status-change", label: "Status change", effect: "Makes power, confidence, access or belonging visibly shift.", evidence: "Blocking, interruption, permission, possession, language or who controls the next action.", failure: "Characters say power changed but behaviour remains identical.", workspace: "Scene Pulse, Dialogue and Character Proof" },
  { id: "withholding-release", label: "Withholding and release", effect: "Controls when information, emotion or action becomes available.", evidence: "Delayed answer, blocked view, silence, partial disclosure or earned confession.", failure: "Withholding feels arbitrary or the release has no consequence.", workspace: "Dialogue in Motion and PageFlow" },
  { id: "spectacle-intimacy", label: "Spectacle and intimacy", effect: "Creates a memorable audience event through scale, form, vulnerability or concentrated attention.", evidence: "Distinctive staging, emotional exposure, sensory design or irreversible action.", failure: "Production scale substitutes for dramatic impact.", workspace: "Storyboard, Production and screenplay" },
  { id: "parallel-juxtaposition", label: "Parallel and juxtaposition", effect: "Lets two events comment on each other through placement and contrast.", evidence: "Intercut action, mirrored choices, repeated spaces or simultaneous consequences.", failure: "The relationship between strands is unclear or redundant.", workspace: "Structure, intercutting and Story Threads" },
] as const;

export const scenePulseLearningOverlay = [
  { term: "Pressure Lock", meaning: "The incompatible force that prevents the scene driver from simply obtaining the objective.", why: "Without resistance, the scene may become information transfer.", evidence: "Scene opposition, conflict, obstacle or incompatible result.", experiment: "Give the opposing force a result it must protect, then test a new tactic.", field: "Scene opposition / conflict" },
  { term: "Cut Line", meaning: "The latest useful entry and earliest decisive exit for the scene.", why: "It protects momentum and emphasizes the dramatic event.", evidence: "Entry condition, exit condition, outcome, final image, line or refusal.", experiment: "Remove the first and last beat; restore only what makes the change understandable.", field: "Entry / exit condition" },
  { term: "Pivot", meaning: "A discovery, refusal, interruption or reversal that makes the opening tactic insufficient.", why: "It forces adaptation and prevents one-level scenes.", evidence: "Reversal, turn, changed tactic or new information.", experiment: "Move the discovery earlier and require a different strategy.", field: "Reversal / turn" },
  { term: "Value flip", meaning: "A practical, relational or emotional condition that changes between entry and exit.", why: "It proves the scene earned screen time.", evidence: "Trust, control, safety, status, hope, belonging or knowledge changes visibly.", experiment: "State the entry and exit values as opposites or changed degrees, then add playable proof.", field: "Entry / exit condition" },
  { term: "Handoff", meaning: "The consequence, question, choice or threat that makes the next movement necessary.", why: "It creates causal and emotional continuity between scenes.", evidence: "Outcome, exit condition and the next scene's objective or pressure.", experiment: "Rewrite the scene ending as a demand placed on what follows.", field: "Outcome / next scene entry" },
] as const;

export const advancedFormattingTemplates = [
  { id: "mini-slug", label: "Secondary heading / mini-slug", purpose: "Move within an established location without repeating a full master heading.", form: "KITCHEN\n\nMara checks the locked window.", preserves: "Readable Fountain/FDX scene geography when kept as a distinct heading or action convention.", misuse: "Using mini-slugs before the master location is established.", layer: "Spec screenplay or production draft" },
  { id: "montage", label: "Montage", purpose: "Compress a process or transformation through selected images.", form: "MONTAGE — THE TOWN PREPARES\n\n— Boards cover the library windows.\n— Radios vanish from shop counters.\n— A child chalks names on the seawall.\n\nEND MONTAGE", preserves: "Clear action sequence in Fountain and FDX; PDF preserves the visible list.", misuse: "Using montage for unrelated events with no cumulative movement.", layer: "Spec screenplay" },
  { id: "series-shots", label: "Series of shots", purpose: "Present brief connected images without implying a full dramatic montage arc.", form: "SERIES OF SHOTS\n\nA) The elevator stalls at Floor 9.\nB) Emergency lights blink red.\nC) A hand releases the stop button.", preserves: "Readable action grouping across export formats.", misuse: "Over-numbering ordinary action or dictating unnecessary coverage.", layer: "Spec or production draft" },
  { id: "intercut", label: "Intercutting", purpose: "Alternate simultaneous or related action while preserving the relationship between locations.", form: "INTERCUT — MARA'S CAR / CONTROL ROOM\n\nMARA\nKill the signal.\n\nDEV watches the timer reach zero.", preserves: "Fountain and FDX keep scene and dialogue order; PDF shows the editorial relationship.", misuse: "Intercutting strands that do not affect or interpret each other.", layer: "Spec screenplay" },
  { id: "phone-remote", label: "Phone or remote conversation", purpose: "Clarify whether participants share a location, are intercut or one side remains unheard.", form: "MARA (V.O.)\nYou already opened it.\n\nDev looks at the sealed case.", preserves: "Character extensions and scene order in Fountain/FDX/PDF.", misuse: "Using V.O. for dialogue heard through a phone when O.S. or an intercut scene is clearer.", layer: "Spec screenplay" },
  { id: "vo-os", label: "V.O. and O.S.", purpose: "Distinguish narration/voice beyond the immediate scene from a speaker physically present but off screen.", form: "MARA (O.S.)\nDon't touch that.\n\nLater—\n\nMARA (V.O.)\nI told myself the warning was enough.", preserves: "Character extensions in Fountain and FDX.", misuse: "Using narration to explain meaning already available through action.", layer: "Spec screenplay" },
  { id: "dual-dialogue", label: "Dual dialogue / overlap", purpose: "Show two speeches intended to occur simultaneously when the overlap matters dramatically.", form: "MARA\nWe leave now.\n\nDEV ^\nWe finish this.", preserves: "Fountain caret syntax and FDX dual-dialogue structures where supported.", misuse: "Formatting ordinary interruptions as continuous dual dialogue.", layer: "Spec or production draft" },
  { id: "insert", label: "Insert / on-screen text / selected shot", purpose: "Direct attention to essential readable information or an image with dramatic meaning.", form: "INSERT — PHONE SCREEN\n\nNO SERVICE. 00:14 REMAINING.", preserves: "Readable action/shot element in Fountain/FDX/PDF.", misuse: "Turning the script into a shot list or highlighting nonessential objects.", layer: "Spec when essential; production draft when coverage matters" },
  { id: "transition", label: "Transition", purpose: "Name an editorial relationship when the transition itself creates meaning.", form: "MATCH CUT TO:\n\nEXT. DRY LAKE — DAWN", preserves: "Transition elements in Fountain and FDX; PDF displays the cue.", misuse: "Adding CUT TO after every scene.", layer: "Spec screenplay when meaningful" },
  { id: "section-note", label: "Section, synopsis and note", purpose: "Organize Fountain drafts and internal planning without becoming screenplay content.", form: "# Sequence 4 — The Signal\n\n= Mara chooses the public broadcast.\n\n[[Check transmitter continuity.]]", preserves: "Fountain source; FDX/PDF behaviour depends on exporter and internal-note settings.", misuse: "Leaving planning notes visible in a submission draft.", layer: "Internal planning layer" },
  { id: "boneyard", label: "Omission / boneyard", purpose: "Temporarily remove material while preserving it in the draft source.", form: "/*\nINT. OLD STATION — NIGHT\nThe abandoned version of the reveal.\n*/", preserves: "Fountain source but normally omits the text from rendered pages.", misuse: "Treating hidden material as canonical or forgetting it contains sensitive/private text.", layer: "Internal drafting layer" },
] as const;

export function storyCraftContextRecommendations(context: { blockNumber: number; miniBlockNumber: number; scenePurpose?: string; theme?: string; tone?: string; screenplayCount: number }) {
  const ids = [
    context.blockNumber <= 4 ? "essentials-experience" : context.blockNumber <= 12 ? "essentials-pacing" : context.blockNumber <= 18 ? "essentials-theme" : "essentials-audit",
    context.miniBlockNumber === 1 ? "essentials-tone" : context.miniBlockNumber === 2 ? "essentials-screen-evidence" : context.miniBlockNumber === 3 ? "essentials-scene" : "essentials-motif",
    context.screenplayCount ? "essentials-formatting" : "essentials-experience",
  ];
  if (!context.scenePurpose) ids.push("essentials-scene");
  if (!context.theme) ids.push("essentials-theme");
  if (!context.tone) ids.push("essentials-tone");
  return [...new Set(ids)];
}

const sourceNote = "PlotPickled from seven legacy Essentials resources into a connected why → how → evidence → diagnose → revise path. Original titles and major terms remain searchable while genre, structure, theme, pacing, symbolism and formatting are taught as flexible tools rather than universal rules.";
function lesson(input: Omit<StoryCraftLesson, "collection" | "sourceNote" | "workspaceLabel" | "workspaceHref">): StoryCraftLesson {
  return { ...input, collection: "Story Craft Essentials", sourceNote, workspaceLabel: "Story Craft Essentials workspace", workspaceHref: "/story-craft-essentials" };
}

export const storyCraftLessons: StoryCraftLesson[] = [
  lesson({ id: "essentials-experience", number: 69, path: "Foundations", title: "Build the Story Experience", duration: "25–35 min", overview: "Connect premise, genre, audience, tone, emotional promise and the ending after-effect before choosing techniques.", objectives: ["Define the audience contract.", "Separate plot, story, structure, style and theme.", "Create a compact Story Experience Card."], sections: [{ heading: "Whose experience is this?", paragraphs: ["Define whose experience anchors the film, what the audience is invited to hope, fear, question or anticipate, the dominant genre promise, intended emotional movement, signature pressure or move and what should remain after the ending.", "Plot is what changes. Story is why those changes matter to people. Structure arranges pressure, choice and consequence. Style selects and presents the experience. Theme is the human question tested by that arrangement."], points: ["Audience promise", "Emotional movement", "Dominant and secondary genre", "Tone and tonal range", "Central question", "Expected and alternative answers", "Signature image, sound or movement", "Ending after-effect"] }], definitions: [{ term: "Audience promise", meaning: "The kind of experience, question and payoff the film invites viewers to expect." }, { term: "Story Experience Card", meaning: "A compact reference for promise, genre, tone, question, signatures and ending effect." }], example: { title: "A tense family mystery", text: "The plot concerns a missing recording. The experience promises intimate suspicion, dry humour and the fear that recovering the truth may end the family." }, checklist: ["Anchor perspective named.", "Audience hope/fear/question stated.", "Genre and tonal range defined.", "Ending after-effect recorded."], mistakes: ["Listing genre without its audience promise.", "Treating theme as a slogan.", "Confusing plot mechanics with emotional experience."], exercise: "Create the active project's Story Experience Card and find one current field or screenplay image that proves each line.", apply: "Treatment", tags: ["Essential Aspects 1", "premise", "genre", "audience", "tone", "story promise", "The Pickle"], sourceAliases: ["Essential Aspects 1"], workspaceSection: "experience", focus: "experience" }),
  lesson({ id: "essentials-pacing", number: 70, path: "Structure", title: "Control Pacing Through Change", duration: "30–40 min", overview: "Measure pacing by the rate and pattern of meaningful change—not genre speed, action quantity or page count alone.", objectives: ["Track meaningful change.", "Use compression, expansion and release.", "Compare planned and observed movement."], sections: [{ heading: "Change creates pace", paragraphs: ["Track frequency and size of condition changes, urgency, information reveal or reinterpretation, tactic changes, reversals, sentence and scene density, visual duration, silence, transitions, handoffs and audience processing time.", "A quiet scene may move quickly if a relationship changes irreversibly. An action sequence may feel slow when it repeats the same obstacle without changing strategy, cost or information."], points: ["Compression", "Expansion", "Acceleration", "Release", "Anticipation", "Processing time", "Handoff"] }], definitions: [{ term: "Pacing", meaning: "The rate and pattern at which meaningful conditions, information, pressure and anticipation change." }, { term: "Release", meaning: "Deliberate space that lets the audience process, contrast or anticipate." }], example: { title: "Fast quiet scene", text: "A mother silently signs away guardianship in forty seconds. Nothing physically large happens, but status, belonging and future options change at once." }, checklist: ["Each movement changes conditions.", "Stillness is deliberate.", "Repeated obstacles change strategy or cost.", "Handoffs sustain anticipation."], mistakes: ["Assuming comedy is fast and drama slow.", "Treating constant intensity as good pacing.", "Using estimated length as the only signal."], exercise: "Map pressure, information change, emotional intensity, tone and handoff across the active Block's scenes.", apply: "Block plan", tags: ["Storytelling Dynamics", "pacing", "Story Clock", "compression", "expansion", "Scene Pulse"], sourceAliases: ["Storytelling Dynamics", "Essential Aspects 1"], workspaceSection: "pacing", focus: "pacing" }),
  lesson({ id: "essentials-tone", number: 71, path: "Craft", title: "Design Tone Without Monotony", duration: "25–35 min", overview: "Treat tone as the story's attitude toward people, events and consequences, expressed through evidence rather than one mood adjective.", objectives: ["Define tonal promise and range.", "Use contrast and controlled turns.", "Find tone in evidence."], sections: [{ heading: "Attitude, not one mood", paragraphs: ["Tone comes from point of view, narrative distance, consequence, image, sound, rhythm, diction and character-specific carriers. Humour can exist inside darkness and seriousness inside comedy.", "Tonal rupture is usually caused by inconsistent consequence or point of view, not emotional variety. Tone may evolve as the story changes."], points: ["Tonal promise", "Emotional palette", "Narrative distance", "Contrast", "Controlled tonal turn", "Character-specific carrier", "Image and sound", "Consequence"] }], definitions: [{ term: "Tone", meaning: "The work's attitude toward its people, events and consequences." }, { term: "Tonal rupture", meaning: "A shift that breaks the established point of view or consequence logic without purposeful preparation." }], example: { title: "Humour under threat", text: "A frightened medic keeps correcting grammar during an evacuation. The humour reveals control strategy; casualties still carry full consequence." }, checklist: ["Tone has screenplay evidence.", "Range is intentional.", "Consequences remain coherent.", "The ending evolves or fulfils the promise."], mistakes: ["Demanding one emotion throughout.", "Using adjectives without images or behaviour.", "Calling any contrast inconsistent."], exercise: "Identify an image, action, dialogue rhythm, sound idea and consequence that currently produce the intended tone.", apply: "Screenplay", tags: ["Storytelling Dynamics", "tone", "emotional palette", "visual language", "Sonic Bible"], sourceAliases: ["Storytelling Dynamics", "Essential Aspects 1"], workspaceSection: "experience", focus: "tone" }),
  lesson({ id: "essentials-theme", number: 72, path: "Craft", title: "Make Theme a Dramatic Argument", duration: "30–40 min", overview: "Develop theme as a contested question tested through beliefs, choices and consequences rather than a moral every element repeats.", objectives: ["Separate topic and theme.", "Map competing answers.", "Find choice-and-consequence proof."], sections: [{ heading: "The argument stays alive", paragraphs: ["Define the topic, central question or proposition, anti-theme or competing answer, character beliefs and strategies, evidence that makes more than one answer plausible, choices that test them and consequences that refine or overturn them.", "Subplots and relationships can run alternate experiments. The climax may prove, refuse, compromise or tragically fail the emerging answer. The ending image and reflection provide the final interpretive frame."], points: ["Central question", "Expected answer", "Competing answer", "Character embodiment", "Key choice", "Consequence", "Climax proof", "Ending reflection"] }, { heading: "Contribution without repetition", paragraphs: ["A scene does not need to state or visibly repeat the theme. It contributes when it changes the conditions under which the question will eventually be answered.", "Excessive thematic agreement can make the story preachy and predictable. Unsupported or one-sided arguments are questions for review, not automatic errors."] }], definitions: [{ term: "Theme", meaning: "A live human question or contested proposition tested by the story's choices and consequences." }, { term: "Anti-theme", meaning: "A credible competing answer, strategy or worldview." }], example: { title: "Safety versus truth", text: "One relationship rewards concealment, another rewards exposure, and the climax forces a choice whose consequence complicates both answers." }, checklist: ["Question is contestable.", "Both answers have credible evidence.", "Choices change the argument.", "Ending reframes the question."], mistakes: ["Announcing the moral.", "Making every line repeat the theme.", "Giving the counter-answer no credible success."], exercise: "Build a Theme Argument Map linking the active question, two answers, characters, Story Threads, choices, consequences and ending reflection.", apply: "Treatment", tags: ["Thematic Components", "Essential Aspects 2", "theme", "anti-theme", "dramatic argument", "Resonance"], sourceAliases: ["Thematic Components", "Essential Aspects 2"], workspaceSection: "theme", focus: "theme" }),
  lesson({ id: "essentials-scene", number: 73, path: "Drafting", title: "Write Scenes That Change Conditions", duration: "30–40 min", overview: "Connect entry, purpose, driver, objective, opposition, tactic, pivot, value change, outcome, exit and handoff through Scene Pulse evidence.", objectives: ["Find the indispensable job.", "Create a playable pivot and value change.", "Hand consequence forward."], sections: [{ heading: "Complete scene movement", paragraphs: ["Define entry condition, indispensable purpose, driver and immediate objective, opposition or incompatible result, tactic and action, pressure and complication, pivot/discovery/refusal/reversal, changed value or relationship state, outcome, consequence, exit condition and handoff.", "A scene does not require a formulaic miniature beginning, middle and end. It must create meaningful change or deliver necessary experience that cannot be achieved more effectively elsewhere. Scene type describes delivery—not purpose."], points: scenePulseLearningOverlay.map((item) => `${item.term}: ${item.meaning}`) }], definitions: [{ term: "Scene purpose", meaning: "The indispensable dramatic job only this scene can perform in its current place." }, { term: "Handoff", meaning: "The result that makes the next movement necessary." }], example: { title: "Reaction scene with a turn", text: "A character enters planning to hide a death, sees a child repeat the victim's gesture and exits choosing public confession. The scene is quiet but changes strategy, theme and the next objective." }, checklist: ["Entry and exit differ.", "Someone drives a result.", "Opposition is incompatible.", "Pivot changes strategy.", "Handoff creates necessity."], mistakes: ["Treating dialogue or action as purpose.", "Ending after information delivery.", "Forcing a formula instead of meaningful change."], exercise: "Use the Scene Pulse overlay on the active scene and run one revision experiment for its weakest term.", apply: "Block plan", tags: ["Scene Writing", "Scene Pulse", "Pressure Lock", "Cut Line", "pivot", "value flip", "handoff"], sourceAliases: ["Scene Writing", "Essential Aspects 1"], workspaceSection: "scene-pulse", focus: "scene" }),
  lesson({ id: "essentials-screen-evidence", number: 74, path: "Drafting", title: "Turn Inner Meaning Into Screen Evidence", duration: "30–40 min", overview: "Translate internal claims into selected visible, audible or performable evidence while avoiding exhaustive description and routine camera direction.", objectives: ["Convert abstractions to evidence.", "Select meaningful visual and sonic detail.", "Use narration intentionally."], sections: [{ heading: "Make the claim playable", paragraphs: ["Translate she feels trapped, he has become his father, the town is losing hope or their relationship changes through action and refusal, altered objective or tactic, objects used differently, spatial distance, blocking, visual contrast, sound, silence, dialogue, subtext, repeated behaviour with variation and performance opportunity.", "Voice-over or narration may be used when the device creates meaning unavailable through ordinary scene action. Ordinary action lines cannot simply enter a character's mind."] }, { heading: "Selection is visual writing", paragraphs: ["Visual writing directs attention and dramatic meaning. It does not inventory every object or routinely dictate camera coverage. Choose the action, detail, image or sound that changes audience understanding.", "Detailed description is not automatically cinematic. Production shots belong where coverage and continuity need separate planning."] }], definitions: [{ term: "Screen evidence", meaning: "Visible, audible or performable material from which the audience can infer story meaning." }, { term: "Narration device", meaning: "An intentional voice, text or formal layer that adds meaning unavailable through ordinary scene action." }], example: { title: "The town is losing hope", text: "The memorial candle stall changes from honour system to locked cabinet; the church bell stops halfway; nobody looks up." }, checklist: ["Claim becomes observable.", "Detail changes meaning.", "Narration earns its use.", "Description remains selective."], mistakes: ["Writing internal thought as fact.", "Listing décor instead of action.", "Using camera directions for routine clarity."], exercise: "Convert one abstract active-project statement into action, blocking, sound, dialogue/subtext and one repeated detail with changed meaning.", apply: "Screenplay", tags: ["Scene Writing", "visual writing", "PageFlow", "inner thought", "blocking", "sound", "performance"], sourceAliases: ["Scene Writing", "Essential Aspects 1"], workspaceSection: "evidence", focus: "evidence" }),
  lesson({ id: "essentials-motif", number: 75, path: "Craft", title: "Build Motifs, Symbols and Echoes", duration: "30–40 min", overview: "Create recurring meaning through literal introduction, changed repetition, behaviour, consequence and payoff rather than fixed symbol dictionaries.", objectives: ["Distinguish symbolic techniques.", "Track meaning shifts.", "Connect visual and sonic continuity."], sections: [{ heading: "Pattern through context and change", paragraphs: ["Distinguish image, recurring detail, motif, symbol, metaphor, visual or sonic rhyme, foreshadowing, setup/payoff, dramatic irony, allegorical design and opening/closing echo.", "Introduce the element literally, repeat it under changed circumstances, let behaviour or consequence alter its meaning, then pay it off, reverse it or leave it deliberately unresolved. The pattern should support the story rather than ask the audience to solve a private puzzle."], points: ["Visual", "Object", "Location", "Action", "Dialogue", "Sound", "Music", "Colour", "Relationship"] }, { heading: "Meaning is not universal", paragraphs: ["A colour, object, name or archetype gains meaning through culture, context, repetition and change. Colour design should account for production context, accessibility and variation rather than a universal lookup table.", "Foreshadowing is not merely hiding a clue; it creates a later relationship between expectation and consequence."] }], definitions: [{ term: "Motif", meaning: "A recurring element whose repetitions accumulate or change meaning." }, { term: "Symbol", meaning: "An element that carries meaning beyond its literal function because the story establishes that relationship." }], example: { title: "The emergency tone", text: "It first signals safety testing, later interrupts a lie, then fails during the real disaster; the final silence becomes the echo." }, checklist: ["Literal context clear.", "Repetitions vary.", "Meaning changes through action.", "Continuity requirements recorded."], mistakes: ["Using fixed symbol meanings.", "Repeating without variation.", "Making the pattern legible only to the writer."], exercise: "Create a Motif and Echo Ledger entry with introduction, repetitions, meaning shifts, associated people/places/threads and payoff or unresolved ending.", apply: "Treatment", tags: ["Symbolic Techniques", "motif", "symbol", "foreshadowing", "irony", "allegory", "opening closing echo", "Resonance"], sourceAliases: ["Symbolic Techniques", "Thematic Components"], workspaceSection: "motif", focus: "motif" }),
  lesson({ id: "essentials-formatting", number: 76, path: "Drafting", title: "Use Advanced Screenplay Forms Clearly", duration: "35–45 min", overview: "Choose montage, mini-slugs, intercutting, voice extensions, dual dialogue, inserts, transitions and internal Fountain tools for dramatic purpose—not decoration.", objectives: ["Understand dramatic purpose and readable form.", "Preview export behaviour.", "Separate spec, production and planning layers."], sections: [{ heading: "Technique follows purpose", paragraphs: ["For each form, identify the dramatic purpose, correct readable form, what Fountain/FDX/PDF preserves, common misuse and whether it belongs in a spec screenplay, production draft or internal planning layer.", "More technical notation does not make a screenplay more cinematic. Use only the form needed to clarify action, time, location, simultaneous strands, off-screen delivery or editorial meaning."], points: advancedFormattingTemplates.map((item) => `${item.label}: ${item.purpose}`) }, { heading: "Advanced forms", paragraphs: ["Cover master headings, mini-slugs, continuous movement, montage, series of shots, intercutting, remote conversations, V.O., O.S., dual dialogue, overlap, inserts, on-screen text, selected shots, meaningful transitions, Fountain sections/synopses/notes, omissions and boneyards.", "Preview generated text before insertion and preserve manual editing. Internal notes and boneyards may contain private material and should not appear in submission exports."] }], definitions: [{ term: "Mini-slug", meaning: "A short secondary heading used after a master location is established." }, { term: "Boneyard", meaning: "Fountain syntax that keeps text in source while omitting it from rendered screenplay pages." }], example: { title: "Intercut with consequence", text: "A remote warning and a silent control-room countdown alternate because each line changes the other location's available choice." }, checklist: ["Purpose stated.", "Readable form previewed.", "Export behaviour understood.", "Layer appropriate.", "Manual edit preserved."], mistakes: ["Adding transitions after every scene.", "Using montage for unrelated events.", "Leaving notes in submission pages.", "Treating formatting as decoration."], exercise: "Choose one advanced form for the active scene, edit the template and review the generated Fountain-style text before copying it manually.", apply: "Screenplay", tags: ["Beyond Sluglines", "montage", "series of shots", "intercut", "V.O.", "O.S.", "dual dialogue", "mini-slug", "Fountain", "FDX"], sourceAliases: ["Beyond Sluglines"], workspaceSection: "formatting", focus: "formatting" }),
  lesson({ id: "essentials-audit", number: 77, path: "Revision", title: "Run the Essential Craft Audit", duration: "40–55 min", overview: "Review promise, causality, character, pressure, scenes, theme, pace, tone, evidence, motifs, dialogue, genre, formatting, continuity and priorities in a deliberate order.", objectives: ["Diagnose with evidence and questions.", "Separate symptoms from root causes.", "Create bounded revision priorities."], sections: [{ heading: "Why → how → evidence → diagnose → revise", paragraphs: ["Begin with the intended audience experience and dramatic function, inspect project and screenplay evidence, ask what produced the current result, then choose a focused experiment. The audit does not calculate a universal screenplay score or rewrite automatically.", "Revision improves purpose, evidence and execution through focused passes; it does not produce an objectively perfect final draft."], points: storyCraftAuditSteps.map((item, index) => `${index + 1}. ${item}`) }, { heading: "Questions, not verdicts", paragraphs: ["A quiet scene, long description, repeated motif, unusual format or unresolved question may be deliberate. Findings should cite evidence, name uncertainty and route the writer to the field or engine that can test the concern.", "Manual writing and no-AI workflows remain complete. Optional AI may help assemble or compare a bounded pass, but output remains non-canonical until explicit approval."] }], definitions: [{ term: "Craft audit", meaning: "An ordered evidence review used to identify questions, root causes and revision priorities." }, { term: "Revision experiment", meaning: "A bounded change used to test a specific diagnosis while preserving the original." }], example: { title: "Tension note with a root cause", text: "The audit finds not that Act Two is slow, but that three scenes repeat the same tactic and handoff without new cost or information. The revision priority becomes leverage change, not arbitrary cutting." }, checklist: ["Promise reviewed first.", "Evidence cited.", "Root cause separated from symptom.", "Priority bounded.", "Original preserved."], mistakes: ["Scoring every technique.", "Rewriting before diagnosis.", "Treating a checklist as a formula.", "Calling a draft perfect or final."], exercise: "Run the fourteen-step audit and record three evidence-based questions, one root cause and one bounded next pass.", apply: "Screenplay", tags: ["Essential Aspects 1", "Essential Aspects 2", "DraftLens", "CraftLoop", "revision priorities", "evidence audit"], sourceAliases: ["Essential Aspects 1", "Essential Aspects 2"], workspaceSection: "audit", focus: "audit" }),
];

export function storyCraftSearchText(module: StoryCraftLesson) {
  return [module.collection, module.sourceAliases.join(" "), module.sourceNote, module.focus, essentialsLegacySourceMap.map((item) => item.source).join(" "), storyCraftAuditSteps.join(" "), essentialTechniqueLibrary.map((item) => Object.values(item).join(" ")).join(" "), scenePulseLearningOverlay.map((item) => Object.values(item).join(" ")).join(" "), advancedFormattingTemplates.map((item) => Object.values(item).join(" ")).join(" "), "pacing tone theme anti-theme thematic duality symbolism motifs foreshadowing irony allegory sluglines montage intercutting series of shots transitions voice-over off-screen dialogue spectacle audience experience"].join(" ").toLowerCase();
}
