import type { LearningModule } from "./learning-library";

export type CollaborationModelId = "solo-feedback" | "private-review" | "invited-contributor" | "co-writing" | "commissioned" | "production-team" | "public-feedback" | "open-community";

export type WorkingTogetherLesson = LearningModule & {
  collection: "Working Together in PlotPickle";
  sourceAliases: string[];
  sourceNote: string;
  workspaceLabel: string;
  workspaceHref: string;
  focus: "model" | "authority" | "brief" | "proposal" | "review" | "decision" | "rights" | "privacy" | "scale";
};

export const collaborationModels = [
  { id: "solo-feedback", label: "Solo project with occasional feedback", owner: "One project owner", view: "Selected readers or file recipients", comment: "Feedback only", propose: "Only when invited", approve: "Project owner", expectation: "Credit or ownership only when separately agreed", privacy: "Local or private by default", licence: "No open licence implied" },
  { id: "private-review", label: "Private reviewer access", owner: "One project owner", view: "Named reviewers", comment: "Anchored review threads", propose: "Normally no rewrite proposal", approve: "Project owner", expectation: "Review credit or fee only when agreed", privacy: "Confidential/private", licence: "No reuse right implied" },
  { id: "invited-contributor", label: "Invited contributor", owner: "One project owner", view: "Named contributor", comment: "Within the contribution brief", propose: "Bounded proposal", approve: "Owner or delegated maintainer", expectation: "Credit, fee or ownership must be documented", privacy: "Defined by the brief", licence: "Only recorded permission applies" },
  { id: "co-writing", label: "Co-writing partnership", owner: "Shared or agreement-defined", view: "Co-writers and approved reviewers", comment: "Shared creative discussion", propose: "Within agreed authority", approve: "Agreement-defined", expectation: "Authorship, ownership and credit require a written understanding", privacy: "Usually private during development", licence: "Joint licensing requires relevant owners" },
  { id: "commissioned", label: "Commissioned rewrite or specialist service", owner: "Commissioning party or agreement-defined", view: "Commissioned contributor", comment: "Scope and acceptance criteria", propose: "Deliverable proposal", approve: "Commissioning decision-maker", expectation: "Compensation, credit and rights follow the agreement", privacy: "Usually confidential", licence: "Contract or permission controls reuse" },
  { id: "production-team", label: "Production-team collaboration", owner: "Producer, company or agreement-defined", view: "Authorized departments", comment: "Area-specific review", propose: "Specialist assets and changes", approve: "Department lead plus canonical authority", expectation: "Employment, service or licence terms apply", privacy: "Production policy", licence: "Asset-specific permission required" },
  { id: "public-feedback", label: "Public feedback project", owner: "Named project owner", view: "Public", comment: "Community feedback", propose: "Only when contributor rules permit", approve: "Owner or maintainers", expectation: "Public visibility does not create ownership or reuse rights", privacy: "Public material only", licence: "Separate explicit licence decision" },
  { id: "open-community", label: "Openly licensed community project", owner: "Named owner or governance group", view: "Public", comment: "Public review", propose: "Under contributor rules", approve: "Governance-defined maintainers", expectation: "Attribution and contributor terms must be explicit", privacy: "Public", licence: "Recorded open licence governs covered material only" },
] as const;

export const collaborationRoles = [
  { role: "Project Owner", authority: "Controls canon, repository connection, rights settings and final acceptance unless a written agreement shares authority." },
  { role: "Co-owner / Maintainer", authority: "May share final approval, licence or invitation authority only when explicitly authorized." },
  { role: "Writer / Co-writer", authority: "Creates story or screenplay material within an agreed scope; ownership and approval remain separate questions." },
  { role: "Contributor", authority: "Proposes bounded additions or changes without automatically controlling canon." },
  { role: "Reviewer", authority: "Comments and identifies questions without changing the approved project." },
  { role: "Story Editor", authority: "Diagnoses and recommends revisions but does not automatically own, approve or merge them." },
  { role: "Research / Continuity Contributor", authority: "Supplies sourced facts, canon checks or continuity findings with provenance." },
  { role: "Visual, Music or Production Contributor", authority: "Supplies specialist assets with permission, credit and provenance information." },
] as const;

export const authorityActions = ["View", "Comment", "Create review threads", "Propose changes", "Edit collaborator records", "Approve specialist assets", "Merge into canon", "Change licences", "Invite or remove collaborators"] as const;
export const feedbackCategories = ["required", "continuity", "rights", "craft", "question", "preference", "praise"] as const;
export const decisionOutcomes = ["accepted", "changes-requested", "question", "deferred", "declined", "superseded", "withdrawn", "resolved-without-change"] as const;
export const contributionBriefTemplates = ["Feedback only", "Rewrite proposal", "Alternative scene or Block", "Dialogue pass", "Character or world contribution", "Research or continuity check", "Storyboard, music or production asset", "Pitch or marketing material"] as const;

export const legacyCollaboratorSourceMap = [
  { source: "Your Role and Key Questions", lessonId: "working-together-model" },
  { source: "Process Post-Submission", lessonId: "working-together-canon" },
  { source: "Feedback and Communication", lessonId: "working-together-review" },
  { source: "Unlimited Contributions", lessonId: "working-together-scale" },
  { source: "Evolving Together", lessonId: "working-together-disagreements" },
  { source: "Act review questions", lessonId: "working-together-review" },
  { source: "Afterglow collaborator guide", lessonId: "working-together-model" },
] as const;

export function collaborationReviewQuestions(blockNumber: number, miniBlockNumber: number) {
  const act = Math.min(4, Math.max(1, Math.ceil(blockNumber / 6)));
  const common = [`What approved fact, relationship, Story Thread or production assumption could this Block ${blockNumber}.${miniBlockNumber} change?`, "What audience experience or story purpose is the contribution intended to improve?", "Which later elements depend on the proposed change?"];
  const actQuestions = act === 1
    ? ["Does this clarify the story promise, world, character condition or originating problem?", "Does it contradict approved setup or Catalyst material?"]
    : act === 2
      ? ["Does it alter the protagonist's objective, strategy, pressure or relationships?", "Does it create a consequence that affects later Blocks?"]
      : act === 3
        ? ["Does it follow from earlier choices and setups?", "Which arc, Story Thread or payoff now requires adjustment?"]
        : ["Does the ending answer the central dramatic question?", "Does the final choice prove change, refusal or consequence?"];
  return [...common, ...actQuestions];
}

const sourceNote = "PlotPickled from the legacy Afterglow collaborator welcome and feedback guide. Original phrases remain searchable, while the method now supports private, commissioned, co-written, production, public-feedback and openly licensed projects without assuming public access or CC BY-SA.";
function lesson(input: Omit<WorkingTogetherLesson, "collection" | "sourceNote" | "workspaceLabel" | "workspaceHref">): WorkingTogetherLesson {
  return { ...input, collection: "Working Together in PlotPickle", sourceNote, workspaceLabel: "Working Together workspace", workspaceHref: "/working-together" };
}

export const workingTogetherLessons: WorkingTogetherLesson[] = [
  lesson({ id: "working-together-model", number: 52, path: "Industry", title: "Choose the Collaboration Model", duration: "20–30 min", overview: "Define ownership, access, proposal rights, approval authority, privacy, credit and licensing before inviting anyone.", objectives: ["Compare eight models.", "Separate access, ownership and reuse.", "Set response and confidentiality expectations."], sections: [{ heading: "The operating agreement", paragraphs: ["The model defines who owns the current project, who may view, comment or propose, who decides canon and what credit, compensation, ownership, confidentiality or licence expectations apply.", "Ordinary collaboration may remain local-only or use file exchange. GitHub, AI, public publishing and an open licence remain optional tools and separate decisions."], points: collaborationModels.map((item) => `${item.label}: ${item.owner}; ${item.privacy}; ${item.licence}.`) }], definitions: [{ term: "Collaboration model", meaning: "The agreed structure for access, contribution, authority, privacy, credit, ownership and reuse." }], example: { title: "Private reader versus open community", text: "Both may use PlotPickle; only the second uses explicit open contributor terms." }, checklist: ["Owner named.", "Canon authority defined.", "Privacy and licence explicit."], mistakes: ["Assuming feedback creates ownership.", "Confusing public visibility with reuse permission."], exercise: "Choose the active project's collaboration model.", apply: "Treatment", tags: ["Your Role and Key Questions", "Afterglow collaborator guide", "private review", "co-writing", "commissioned", "open licence"], sourceAliases: ["Your Role and Key Questions", "Afterglow collaborator guide"], focus: "model" }),
  lesson({ id: "working-together-authority", number: 53, path: "Industry", title: "Define Roles and Decision Authority", duration: "20–30 min", overview: "Translate creative roles into an authority matrix without confusing them with GitHub permissions.", objectives: ["Define roles.", "Assign authority.", "Separate technical permission."], sections: [{ heading: "Responsibility and enforcement", paragraphs: ["A role states what someone is asked to do and may decide. Technical permission states what an account can do.", "The owner retains final canon authority unless a written agreement establishes shared or delegated authority."], points: collaborationRoles.map((item) => `${item.role}: ${item.authority}`) }, { heading: "Authority matrix", paragraphs: ["Record view, comment, thread, proposal, rights, asset, merge, licence and invitation authority."], points: authorityActions.map((item) => `Authority choice: ${item}`) }], definitions: [{ term: "Creative authority", meaning: "The agreed right to make a project decision." }, { term: "Technical permission", meaning: "The capability to perform an action in a tool." }], example: { title: "Story editor with write access", text: "The editor may propose while the owner still decides canon." }, checklist: ["Role named.", "Scope defined.", "Permissions verified separately."], mistakes: ["Assuming write access means merge authority."], exercise: "Audit one collaborator's authority.", apply: "Treatment", tags: ["roles", "authority matrix", "GitHub permissions"], sourceAliases: ["Your Role and Key Questions"], focus: "authority" }),
  lesson({ id: "working-together-brief", number: 54, path: "Industry", title: "Create a Contribution Brief", duration: "25–35 min", overview: "Turn an open invitation into a bounded assignment with purpose, locks, freedom, rights and acceptance criteria.", objectives: ["Name the problem.", "Anchor the target.", "Record continuity and rights."], sections: [{ heading: "Brief the work", paragraphs: ["Name the contributor, role, decision-maker, target, problem, audience effect, canon locks, elements that must not change, output, freedom, due date, review window, sharing, credit, compensation, ownership, licence and acceptance criteria."], points: contributionBriefTemplates.map((item) => `Template: ${item}`) }], definitions: [{ term: "Contribution brief", meaning: "A structured request defining scope, purpose, locks, deliverable, rights and acceptance." }], example: { title: "Alternative crisis scene", text: "The brief locks earlier facts and requires a changed choice with a new consequence." }, checklist: ["Target anchored.", "Locks listed.", "Acceptance testable.", "Rights referenced."], mistakes: ["Asking someone to improve the story.", "Discussing ownership only after acceptance."], exercise: "Create one brief for the active selection.", apply: "Block plan", tags: ["contribution brief", "continuity locks", "acceptance criteria"], sourceAliases: ["Your Role and Key Questions"], focus: "brief" }),
  lesson({ id: "working-together-canon", number: 55, path: "Industry", title: "Start From the Approved Story", duration: "15–25 min", overview: "Pull or exchange the approved project, work locally and submit a bounded proposal instead of writing directly to canon.", objectives: ["Identify the approved base.", "Work locally.", "Handle stale bases deliberately."], sections: [{ heading: "Safe sequence", paragraphs: ["Pull the approved canonical version for review, compare and deliberately apply it, read the brief and locks, work locally, save backups and submit a bounded proposal. Local-only and file-based collaboration remain fully supported.", "A stale base requires a newly approved pull and human reconsideration; complete creative versions cannot always be mechanically merged."], points: ["Approved story → local draft → proposal → review → decision → canon."] }], definitions: [{ term: "Stale base", meaning: "A proposal based on an older canonical revision." }], example: { title: "Another ending merged first", text: "Pull the new canon and reconsider causality, character and continuity before resubmitting." }, checklist: ["Approved base known.", "Incoming project compared.", "Backup saved."], mistakes: ["Writing directly to canon.", "Forcing a creative merge."], exercise: "Identify the next proposal's exact scope.", apply: "Block plan", tags: ["Process Post-Submission", "approved story", "stale base", ".ppf"], sourceAliases: ["Process Post-Submission"], focus: "proposal" }),
  lesson({ id: "working-together-proposal", number: 56, path: "Industry", title: "Submit a Reviewable Proposal", duration: "20–30 min", overview: "Package purpose, scope, evidence, dependencies, questions and provenance before opening GitHub.", objectives: ["Explain what changed.", "Name dependencies.", "Surface rights and questions."], sections: [{ heading: "Proposal packet", paragraphs: ["Explain what changed and why, audience effect, exact areas, source brief, before-and-after evidence, consequences for characters, continuity, Story Threads, runtime, production and rights, new assumptions, unresolved questions, alternatives, provenance, credit and inspection areas.", "The proposal must be understandable inside PlotPickle before the owner opens GitHub."] }], definitions: [{ term: "Proposal packet", meaning: "Creative context for a reviewable change." }], example: { title: "Dialogue pass", text: "The packet identifies changed scenes, relationship effects, a new canon fact and a permission question." }, checklist: ["Purpose clear.", "Dependencies listed.", "Rights reviewed."], mistakes: ["Using only a vague proposal title.", "Hiding canon assumptions."], exercise: "Create a packet for the active local change.", apply: "Screenplay", tags: ["proposal packet", "before and after", "provenance"], sourceAliases: ["Process Post-Submission"], focus: "proposal" }),
  lesson({ id: "working-together-review", number: 57, path: "Industry", title: "Review the Change, Not the Person", duration: "25–35 min", overview: "Anchor evidence-based feedback, categorize its purpose and separate project requirements from preference.", objectives: ["Categorize feedback.", "Anchor comments.", "Close the loop."], sections: [{ heading: "Evidence first", paragraphs: ["Anchor to a story field, Block, scene, screenplay element or character. Describe audience experience or factual conflict before prescribing a fix. Explain reason and intended outcome and acknowledge retained strengths.", "Act and Block questions are optional lenses that adapt to the active structure; they do not impose one fixed legacy Act model."], points: feedbackCategories.map((item) => `Feedback category: ${item}`) }], definitions: [{ term: "Anchored feedback", meaning: "A review note linked to a canonical project element." }], example: { title: "Continuity before prescription", text: "Mark when a character cannot know a fact and name the intended audience uncertainty." }, checklist: ["Anchor selected.", "Category selected.", "Evidence specific."], mistakes: ["Reviewing the person.", "Treating taste as a requirement."], exercise: "Create one anchored review note.", apply: "Screenplay", tags: ["Feedback and Communication", "Act review questions", "required", "continuity", "preference", "praise"], sourceAliases: ["Feedback and Communication", "Act review questions"], focus: "review" }),
  lesson({ id: "working-together-disagreements", number: 58, path: "Industry", title: "Decide, Disagree and Record Canon", duration: "25–35 min", overview: "Separate discussion, approval and canon and record merge, decline, defer, withdraw or supersede decisions.", objectives: ["Use a decision lifecycle.", "Resolve disagreements by evidence.", "Record rationale."], sections: [{ heading: "Explicit decision", paragraphs: ["Local draft → proposal → review → changes requested or approved → owner/maintainer merge → canonical pull.", "Restate the goal and brief, isolate the disagreement, separate continuity from preference, compare audience effect, causality, character, theme, feasibility and rights, identify final authority and record the decision."], points: decisionOutcomes.map((item) => `Outcome: ${item}`) }], definitions: [{ term: "Decision log", meaning: "A dated outcome, decision-maker, rationale, rights update and follow-up record." }], example: { title: "Two climax approaches", text: "Test both, choose under the authority model and preserve the declined proposal history." }, checklist: ["Authority confirmed.", "Rationale recorded.", "Follow-up created."], mistakes: ["Assuming consensus is required.", "Closing without a reason."], exercise: "Record one proposal decision.", apply: "Treatment", tags: ["Evolving Together", "decision log", "declined", "deferred", "withdrawn", "superseded"], sourceAliases: ["Evolving Together", "Process Post-Submission"], focus: "decision" }),
  lesson({ id: "working-together-rights", number: 59, path: "Industry", title: "Record Credit, Ownership and Permissions", duration: "25–35 min", overview: "Connect accepted work to contributor, agreement, ownership, licence, permission and provenance records.", objectives: ["Record the contributor.", "Separate contribution and ownership.", "Link accepted work."], sections: [{ heading: "Rights distinctions", paragraphs: ["Feedback does not automatically create ownership. A contribution does not automatically transfer copyright. A pull request is not an employment, assignment or licence agreement. A public repository is not an open licence. PlotPickle software and documentation licences do not automatically apply to the user's screenplay.", "Record name, credited-as name, role, contribution, ownership share if any, compensation or commissioned status when documented, agreement or permission reference, linked work and acceptance date."] }], definitions: [{ term: "Agreement reference", meaning: "A pointer to written terms governing role, payment, ownership, credit or permission." }], example: { title: "Accepted storyboard frames", text: "Record artist, asset IDs, fee agreement, permission and acceptance date." }, checklist: ["Contributor linked.", "Agreement referenced.", "Provenance checked."], mistakes: ["Treating a pull request as copyright transfer."], exercise: "Audit one accepted contribution.", apply: "Treatment", tags: ["credit", "ownership", "permissions", "copyright", "licence"], sourceAliases: ["Process Post-Submission"], focus: "rights" }),
  lesson({ id: "working-together-scale", number: 60, path: "Industry", title: "Protect Privacy and Scale the Review Queue", duration: "25–35 min", overview: "Keep unfinished work private and scale through briefs, area owners, statuses, dependencies and explicit canon decisions.", objectives: ["Protect local work.", "Set review capacity.", "Scale bounded proposals."], sections: [{ heading: "Privacy and scale", paragraphs: ["Local drafts, autosaves, AI prompts and private assets do not leave the computer merely because GitHub is connected. Credentials remain outside the .ppf. Only intentionally submitted proposal material is shared.", "Assign briefs, define review owners, limit simultaneous high-risk proposals, track dependencies, group review rounds, archive superseded work and publish realistic response expectations. Unlimited Contributions remains searchable, but projects may define capacity, deadlines and closed areas."], points: ["Community feedback is not automatically an authorized contribution.", "GitHub manages the technical queue; PlotPickle presents creative-project meaning."] }], definitions: [{ term: "Review capacity", meaning: "The realistic volume and timing a project can assess." }], example: { title: "Production team", text: "Area leads review visual, audio, continuity and screenplay briefs while the canon path stays short." }, checklist: ["Privacy defined.", "Capacity realistic.", "Dependencies visible."], mistakes: ["Promising detailed feedback on every submission.", "Uploading third-party material without authority."], exercise: "Define privacy, review owners and proposal limits.", apply: "Treatment", tags: ["Unlimited Contributions", "privacy", "local drafts", "AI prompts", "review queue"], sourceAliases: ["Unlimited Contributions"], focus: "scale" }),
];

export function workingTogetherSearchText(module: WorkingTogetherLesson) {
  return [module.collection, module.sourceAliases.join(" "), module.sourceNote, module.focus, collaborationModels.map((item) => Object.values(item).join(" ")).join(" "), collaborationRoles.map((item) => `${item.role} ${item.authority}`).join(" "), authorityActions.join(" "), feedbackCategories.join(" "), decisionOutcomes.join(" "), contributionBriefTemplates.join(" "), legacyCollaboratorSourceMap.map((item) => item.source).join(" ")].join(" ").toLowerCase();
}
