import type { LearningModule } from "./learning-library";

export type TwentyFourBlocksLesson = LearningModule & {
  collection: "The 24 Blocks Method";
  sourceConcept: string;
  sourceNote: string;
  howPlotPickleApplies: string;
  visual: string[];
  workspaceLink: "Treatment" | "Screenplay" | "Block plan";
};

const lesson = (
  module: Omit<TwentyFourBlocksLesson, "collection" | "sourceNote" | "workspaceLink">,
): TwentyFourBlocksLesson => ({
  ...module,
  collection: "The 24 Blocks Method",
  sourceNote: `Adapted from the original 24 Blocks concept: ${module.sourceConcept}.`,
  workspaceLink: module.apply,
});

export const twentyFourBlocksLessons: TwentyFourBlocksLesson[] = [
  lesson({
    id: "24b-new-spin",
    number: 15,
    path: "Foundations",
    title: "Why 24 Blocks Work",
    sourceConcept: "A New Spin",
    duration: "20–30 min",
    overview: "See the feature screenplay as four acts of six manageable movements: large enough to carry consequence, small enough to revise without losing the whole story.",
    objectives: ["Explain the four-act, six-block rhythm.", "Use Blocks as planning containers rather than fixed beats.", "Connect Blocks to PlotPickle’s 12 sequences and 96 mini-blocks."],
    sections: [
      { heading: "Story reason first", paragraphs: ["A feature becomes easier to design when the writer can see twenty-four meaningful changes instead of one enormous middle. Each Block should alter the dramatic situation through pressure, choice, discovery or consequence."], points: ["Act I: orient and disrupt.", "Act II: pursue and complicate.", "Act III: intensify and transform.", "Act IV: confront and resolve."] },
      { heading: "How PlotPickle applies this", paragraphs: ["PlotPickle groups six Blocks into each act, two Blocks into each sequence and four mini-blocks into each Block. Scenes remain flexible: a Block may contain one long scene, several short scenes or intercut material."], points: ["4 acts", "12 sequences", "24 Blocks", "96 mini-blocks", "Flexible scene count"] },
    ],
    definitions: [{ term: "Block", meaning: "A planning movement that changes the story’s dramatic condition." }, { term: "Sequence", meaning: "A paired set of Blocks with a local objective and turn." }],
    example: { title: "Afterglow orientation", text: "A Block does not mean one scene. An Afterglow Block can move from discovery to denial through several locations while still serving one dramatic movement." },
    checklist: ["The Block changes conditions.", "The protagonist must respond.", "The movement belongs in its act.", "Scene count follows the story."],
    mistakes: ["Treating every Block as equal length.", "Confusing a label with an event.", "Adding filler to occupy a grid cell."],
    exercise: "Name the dramatic change in the active Block in one sentence, then list the scenes needed to earn it.",
    apply: "Block plan",
    tags: ["A New Spin", "24 Blocks", "four acts", "six blocks", "sequence", "planning resolution"],
    howPlotPickleApplies: "Use the active Block planner to define the movement, then let scenes expand or contract around it.",
    visual: ["4 Acts", "12 Sequences", "24 Blocks", "96 Mini-blocks", "Flexible Scenes"],
  }),
  lesson({
    id: "24b-structure-guide",
    number: 16,
    path: "Foundations",
    title: "The Grid Is a Guide, Not a Cage",
    sourceConcept: "Structure Guide",
    duration: "20–30 min",
    overview: "Use the 24-block grid to expose missing movement and weak causality without forcing every screenplay into identical timing or content.",
    objectives: ["Separate structural function from formula.", "Diagnose empty or overloaded Blocks.", "Adjust density while preserving causal movement."],
    sections: [{ heading: "A visible thinking surface", paragraphs: ["The grid helps writers compare what changes, where pressure rises and whether the audience receives enough orientation. It is a diagnostic surface, not a mandatory beat sheet."], points: ["Move a turn when the story earns it.", "Combine Blocks when one movement carries both jobs.", "Split an overloaded Block when several irreversible changes compete."] }, { heading: "How PlotPickle applies this", paragraphs: ["PlotPickle stores the structural purpose separately from scenes, treatment and screenplay pages. You can revise one layer without pretending the others are identical."], points: ["Block function", "Mini-block movement", "Treatment evidence", "Screenplay execution"] }],
    definitions: [{ term: "Planning resolution", meaning: "The level of detail used to see and revise story movement." }, { term: "Structural function", meaning: "The dramatic job a movement performs, regardless of its surface events." }],
    example: { title: "Uneven but coherent", text: "A quiet relationship Block may occupy eight pages while an action pursuit spans three Blocks in ten pages. The grid tracks change, not stopwatch equality." },
    checklist: ["Every Block has a function.", "Adjacent Blocks cause or complicate one another.", "Length follows dramatic need.", "No event exists only to satisfy the template."],
    mistakes: ["Assuming each Block must contain the same number of scenes.", "Forcing a midpoint because a chart says so.", "Mistaking symmetry for meaning."],
    exercise: "Mark one active Block as thin, balanced or overloaded. Revise its function before changing its scenes.",
    apply: "Block plan",
    tags: ["Structure Guide", "grid", "formula", "flexible scenes", "diagnostic"],
    howPlotPickleApplies: "Compare the Block function, mini-blocks and scene list in the active project before rewriting pages.",
    visual: ["Function", "Pressure", "Choice", "Consequence"],
  }),
  lesson({
    id: "24b-structures-role",
    number: 17,
    path: "Craft",
    title: "Structure Creates Pressure and Choice",
    sourceConcept: "Structure’s Role",
    duration: "25–35 min",
    overview: "Understand structure as the arrangement of pressure, decisions, causality and audience orientation—not a list of prescribed incidents.",
    objectives: ["Track cause and consequence.", "Use structure to sharpen choices.", "Control what the audience understands and expects."],
    sections: [{ heading: "Pressure produces decisions", paragraphs: ["Structure becomes dramatic when changing conditions narrow or complicate a character’s choices. Events matter because someone must interpret and answer them."], points: ["New information changes the plan.", "Opposition raises the cost.", "A decision creates the next problem.", "Consequences prevent reset."] }, { heading: "How PlotPickle applies this", paragraphs: ["Block and scene fields separate objective, opposition, turn and consequence so the writer can inspect the causal chain."], points: ["Objective", "Opposition", "Turn", "Consequence", "Handoff"] }],
    definitions: [{ term: "Causality", meaning: "A meaningful relationship in which one action or decision produces the next condition." }, { term: "Audience orientation", meaning: "The information and expectations that help viewers understand what matters now." }],
    example: { title: "Afterglow consequence chain", text: "A discovery matters only when it changes what the protagonist believes, forces a choice and makes the next Block unavoidable." },
    checklist: ["The protagonist faces a real choice.", "The choice changes conditions.", "The next movement grows from the consequence.", "The audience knows what is at stake."],
    mistakes: ["Using coincidence to replace causality.", "Escalating spectacle without changing choices.", "Withholding basic orientation to manufacture confusion."],
    exercise: "Write the current Block as Because → Therefore → But → So. Repair any step that depends on ‘and then.’",
    apply: "Block plan",
    tags: ["Structure’s Role", "pressure", "choice", "causality", "audience orientation"],
    howPlotPickleApplies: "Use Dynamic Scenes and Block diagnostics to test the causal handoff.",
    visual: ["Pressure", "Choice", "Action", "Consequence", "New Pressure"],
  }),
  lesson({
    id: "24b-story-beats",
    number: 18,
    path: "Craft",
    title: "From Beat to Act",
    sourceConcept: "Story Beats",
    duration: "25–35 min",
    overview: "Understand how beats, scenes, mini-blocks, Blocks, sequences and acts nest without treating the levels as interchangeable.",
    objectives: ["Name each structural level.", "Choose the right planning scale.", "Trace a local turn into a feature-level movement."],
    sections: [{ heading: "The hierarchy", paragraphs: ["A beat is the smallest perceptible shift. Beats form scenes; scenes can serve mini-blocks; four mini-block movements complete a Block; paired Blocks form a sequence; six Blocks form an act."], points: ["Beat: moment-to-moment change.", "Scene: continuous dramatic encounter.", "Mini-block: quarter movement.", "Block: meaningful story movement.", "Sequence: local arc.", "Act: major phase of the feature."] }, { heading: "How PlotPickle applies this", paragraphs: ["PlotPickle lets the writer move between hierarchy levels while preserving links. A screenplay scene can be traced back to its mini-block and Block purpose."], points: ["Navigate without flattening.", "Diagnose at the smallest useful level.", "Keep top-level intent visible while drafting."] }],
    definitions: [{ term: "Beat", meaning: "A small shift in tactic, information, emotion, power or intention." }, { term: "Handoff", meaning: "The consequence or unresolved pressure that launches the next unit." }],
    example: { title: "One reveal at six scales", text: "A glance is a beat; the confrontation is a scene; the reveal completes a mini-block; the changed alliance completes a Block; the failed escape completes a sequence; the act ends with a new goal." },
    checklist: ["Each level has a distinct job.", "Scenes serve a larger movement.", "Blocks contain change, not summaries.", "Act turns alter the feature’s direction."],
    mistakes: ["Calling every event a beat.", "Treating one scene as automatically equal to one Block.", "Drafting pages without a larger handoff."],
    exercise: "Take the active scene and write its beat turn, mini-block function, Block change, sequence movement and act purpose.",
    apply: "Screenplay",
    tags: ["Story Beats", "beat", "scene", "mini-block", "sequence", "act", "hierarchy"],
    howPlotPickleApplies: "Use the screenplay-to-mini-block links to move between execution and structure.",
    visual: ["Beat", "Scene", "Mini-block", "Block", "Sequence", "Act"],
  }),
  lesson({
    id: "24b-principle-three",
    number: 19,
    path: "Foundations",
    title: "Promise, Progress, Pressure, Payoff",
    sourceConcept: "Principle of Three",
    duration: "25–35 min",
    overview: "Preserve the original Promise–Progress–Payoff foundation while using PlotPickle’s added Pressure step to strengthen escalation across four mini-blocks.",
    objectives: ["Explain the original triad.", "Distinguish PlotPickle’s added Pressure step.", "Use all four movements without mechanical repetition."],
    sections: [{ heading: "The original foundation", paragraphs: ["Promise establishes the dramatic expectation. Progress develops or complicates it. Payoff fulfils, reverses or meaningfully reframes it. That three-part principle remains the conceptual foundation."], points: ["Promise", "Progress", "Payoff"] }, { heading: "PlotPickle’s expansion", paragraphs: ["PlotPickle adds Pressure between Progress and Payoff. Pressure is the escalation that makes the outcome costly, uncertain or irreversible. It extends the original method; it does not replace or obscure it."], points: ["Promise: establish.", "Progress: develop.", "Pressure: escalate.", "Payoff: deliver and hand off."] }, { heading: "How PlotPickle applies this", paragraphs: ["Each Block’s four mini-block positions carry this movement pattern by default, while writers may adapt the surface events and scene count."], points: ["96 positions across 24 Blocks", "Writer approval", "Flexible scene execution"] }],
    definitions: [{ term: "Promise", meaning: "An expectation the story deliberately creates." }, { term: "Pressure", meaning: "PlotPickle’s added escalation step that intensifies the path to payoff." }, { term: "Payoff", meaning: "A fulfilment, reversal or reframing prepared by earlier story evidence." }],
    example: { title: "Afterglow mini-block movement", text: "Promise: a recovered signal may prove consciousness survived. Progress: the signal answers. Pressure: answering exposes the team. Payoff: the response identifies someone believed dead." },
    checklist: ["The Promise is legible.", "Progress changes understanding.", "Pressure raises cost or uncertainty.", "Payoff uses established evidence.", "The Payoff launches new movement."],
    mistakes: ["Presenting Pressure as part of the original triad.", "Repeating the same information as Progress.", "Delivering a payoff that was never promised."],
    exercise: "Label the four mini-blocks in the active Block as Promise, Progress, Pressure and Payoff. Rewrite the weakest transition.",
    apply: "Block plan",
    tags: ["Principle of Three", "Promise", "Progress", "Pressure", "Payoff", "96 mini-blocks"],
    howPlotPickleApplies: "The Block planner exposes the four positions and keeps the original three-part source concept searchable.",
    visual: ["Promise", "Progress", "Pressure", "Payoff"],
  }),
  lesson({
    id: "24b-dramatic-question",
    number: 20,
    path: "Craft",
    title: "Questions That Pull the Story Forward",
    sourceConcept: "Dramatic Question",
    duration: "25–35 min",
    overview: "Build nested dramatic questions at story, act, sequence, Block and scene levels so curiosity and emotional investment survive between major turns.",
    objectives: ["Write the central story question.", "Create nested local questions.", "Resolve or transform questions deliberately."],
    sections: [{ heading: "Nested curiosity", paragraphs: ["The central question organizes the feature, but viewers also need nearer questions they can track. Each level should matter on its own while contributing to the larger uncertainty."], points: ["Story: can the protagonist achieve the defining objective?", "Act: can they survive or complete this phase?", "Sequence: can the local plan work?", "Block: what changes now?", "Scene: who gets what they want in this encounter?"] }, { heading: "How PlotPickle applies this", paragraphs: ["PlotPickle connects project-level conflict to Block and Dynamic Scene fields so local questions can be audited against the feature’s central pull."], points: ["Central dramatic question", "Sequence question", "Block question", "Scene question"] }],
    definitions: [{ term: "Dramatic question", meaning: "An uncertainty whose answer matters emotionally and causally." }, { term: "Question handoff", meaning: "The way one resolved uncertainty creates or sharpens the next." }],
    example: { title: "Nested Afterglow questions", text: "Story: can consciousness outlive the body? Sequence: can the team verify the signal? Block: will the test remain secret? Scene: will Mara reveal what she heard?" },
    checklist: ["The central question is answerable by the ending.", "Local questions are concrete.", "Answers change conditions.", "Questions do not rely only on withheld exposition."],
    mistakes: ["Confusing theme with a yes/no plot question.", "Keeping every question open until the ending.", "Using vagueness instead of uncertainty."],
    exercise: "Write one question each for the active story, act, sequence, Block and scene. Confirm that each answer changes the next level.",
    apply: "Block plan",
    tags: ["Dramatic Question", "story question", "act question", "sequence question", "block question", "scene question"],
    howPlotPickleApplies: "Use story planning and Dynamic Scenes to connect questions across scales.",
    visual: ["Story", "Act", "Sequence", "Block", "Scene"],
  }),
  lesson({
    id: "24b-structure-diversity",
    number: 21,
    path: "Foundations",
    title: "One Grid, Many Story Shapes",
    sourceConcept: "Structure Diversity",
    duration: "30–40 min",
    overview: "Adapt the 24-block planning resolution to nonlinear, parallel, episodic, circular, framed and other structures without forcing chronological or formulaic sameness.",
    objectives: ["Map presentation order separately from chronology.", "Track parallel and episodic lines.", "Use the grid as resolution rather than beat prescription."],
    sections: [{ heading: "Different shapes, same need for movement", paragraphs: ["Stories can reorder time, alternate protagonists, repeat cycles or accumulate episodes. The audience still needs intelligible changes, controlled questions and meaningful consequences."], points: ["Nonlinear", "Parallel", "Episodic", "Circular", "Framed", "Anthology or mosaic"] }, { heading: "How PlotPickle applies this", paragraphs: ["Blocks represent dramatic movement in presentation order. Timeline and canon tools can separately preserve chronology, character continuity and cross-thread dependencies."], points: ["Presentation order", "Story chronology", "Thread ownership", "Convergence points"] }],
    definitions: [{ term: "Presentation order", meaning: "The order in which the audience receives events." }, { term: "Chronology", meaning: "The order in which events occur inside the story world." }],
    example: { title: "Parallel Afterglow", text: "Two consciousness threads can alternate across Blocks while each maintains its own objective, pressure and payoff before converging in the final act." },
    checklist: ["The form has a dramatic reason.", "Each thread changes.", "Reordered information alters meaning.", "The audience can track essential causality.", "Convergence is prepared."],
    mistakes: ["Using nonlinear order to hide weak causality.", "Giving parallel threads no reason to share the film.", "Treating episodes as unrelated incidents."],
    exercise: "Remap the active story as linear, parallel and circular. Choose the version that creates the strongest audience experience and explain why.",
    apply: "Block plan",
    tags: ["Structure Diversity", "nonlinear", "parallel", "episodic", "circular", "planning resolution"],
    howPlotPickleApplies: "Use Blocks for presentation movement and Timeline/Canon for chronology and continuity.",
    visual: ["Chronology", "Presentation", "Threads", "Convergence"],
  }),
  lesson({
    id: "24b-reflection",
    number: 22,
    path: "Craft",
    title: "Setup, Payoff and the Closing Image",
    sourceConcept: "Reflection",
    duration: "25–35 min",
    overview: "Design reflection as setup, payoff, consequence and meaning—not merely a repeated image—so the ending reveals how the story changed its world and characters.",
    objectives: ["Plant usable setup.", "Create consequential payoff.", "Relate opening and closing images through changed meaning."],
    sections: [{ heading: "Reflection is transformation", paragraphs: ["A closing image gains force when it recalls an earlier condition and proves what changed. Repetition alone is decorative; reflection carries consequence and meaning."], points: ["Setup", "Development", "Consequence", "Payoff", "Meaning"] }, { heading: "How PlotPickle applies this", paragraphs: ["Canon, motif and continuity tools can connect early evidence to later payoffs, while the Block grid reveals whether the closing movement answers the opening promise."], points: ["Opening image", "Motif", "Setup evidence", "Closing image", "Changed context"] }],
    definitions: [{ term: "Setup", meaning: "Information, behaviour or imagery established so a later development can feel earned." }, { term: "Reflection", meaning: "A later moment that recalls an earlier one while revealing changed meaning or consequence." }],
    example: { title: "Afterglow closing relationship", text: "An opening image of a silent machine becomes a closing image of the same machine choosing silence. The composition repeats; the meaning reverses." },
    checklist: ["The payoff has prior evidence.", "The consequence changes interpretation.", "The closing image relates to the opening.", "The ending answers the central dramatic question."],
    mistakes: ["Repeating an image without changed meaning.", "Planting setup immediately before payoff.", "Using symbolism instead of resolving consequence."],
    exercise: "Pair the active project’s opening and closing images. Write what remains visually similar and what the audience now understands differently.",
    apply: "Treatment",
    tags: ["Reflection", "setup", "payoff", "consequence", "closing image", "motif"],
    howPlotPickleApplies: "Link setups and payoffs through Canon, treatment and closing Block evidence.",
    visual: ["Opening", "Setup", "Consequence", "Payoff", "Closing Meaning"],
  }),
  lesson({
    id: "24b-ai",
    number: 23,
    path: "Responsible AI",
    title: "AI at Every Structural Level",
    sourceConcept: "Blocks with AI",
    duration: "30–40 min",
    overview: "Use optional AI to question, compare and propose at beat, scene, mini-block, Block, sequence and act levels while keeping approval, authorship and canon with the writer.",
    objectives: ["Choose the correct structural level for an AI task.", "Bound context and constraints.", "Preserve human approval and project truth."],
    sections: [{ heading: "Match the request to the level", paragraphs: ["A scene-dialogue problem needs different context than an act-level escalation problem. Smaller, clearer context packs reduce invention and make review easier."], points: ["Beat: tactics or subtext alternatives.", "Scene: objective, opposition and turn.", "Mini-block: movement options.", "Block: escalation and payoff.", "Sequence: local arc.", "Act: phase-level diagnosis."] }, { heading: "How PlotPickle applies this", paragraphs: ["AI remains optional. PlotPickle can prepare bounded prompts from the active level, but nothing enters the project or becomes canonical until the writer approves it."], points: ["Generated", "Reviewed", "Revised", "Approved", "Canonical"] }],
    definitions: [{ term: "Context pack", meaning: "Only the project information needed for one bounded task." }, { term: "Approval boundary", meaning: "The separation between a generated proposal and writer-approved project truth." }],
    example: { title: "Block-level request", text: "Propose three Pressure movements for Block 9 using the approved objective, antagonist strategy and world rules. Do not add characters or change the promised Payoff." },
    checklist: ["The structural level is named.", "Context is minimal and relevant.", "Canon locks are explicit.", "Alternatives are reviewed.", "No-AI work remains possible."],
    mistakes: ["Sending the entire project for a local question.", "Accepting fluent output as canon.", "Asking AI to decide authorship-level choices without review."],
    exercise: "Write one bounded AI prompt for the active Block and a second no-AI diagnostic that solves the same problem manually.",
    apply: "Block plan",
    tags: ["Blocks with AI", "AI", "writer approval", "authorship", "context pack", "canon"],
    howPlotPickleApplies: "Use active-level prompts and explicit approval states; AI never becomes required infrastructure.",
    visual: ["Prompt", "Proposal", "Review", "Revision", "Approval", "Canon"],
  }),
  lesson({
    id: "24b-dynamic-scenes",
    number: 24,
    path: "Craft",
    title: "Scenes That Turn and Hand Off",
    sourceConcept: "Dynamic Scenes",
    duration: "30–40 min",
    overview: "Build scenes around objective, opposition, action, reversal, turn, consequence and handoff so every scene changes the story rather than merely explaining it.",
    objectives: ["Give the scene an active objective.", "Create opposition and tactical change.", "End with consequence and a handoff."],
    sections: [{ heading: "The dynamic scene chain", paragraphs: ["A scene begins with someone pursuing something under current conditions. Opposition forces action and adjustment. A reversal or turn changes power, information, emotion or direction. The consequence prevents the screenplay from resetting."], points: ["Objective", "Opposition", "Action", "Reversal", "Turn", "Consequence", "Handoff"] }, { heading: "How PlotPickle applies this", paragraphs: ["Dynamic Scene fields make the chain explicit and connect the scene’s handoff to the next scene or mini-block."], points: ["Scene purpose", "Character tactics", "Visible change", "Next pressure"] }],
    definitions: [{ term: "Turn", meaning: "The scene’s decisive change in power, knowledge, emotion, commitment or direction." }, { term: "Handoff", meaning: "The consequence, question or pressure carried into the next unit." }],
    example: { title: "Afterglow scene turn", text: "Mara enters to conceal the signal. Opposition forces her to play it. The reversal is that it speaks in her own voice. She leaves with a new objective, and the team now distrusts her." },
    checklist: ["Someone wants something now.", "Opposition is active.", "Tactics change.", "The scene turns.", "A consequence survives the cut.", "The next unit inherits pressure."],
    mistakes: ["Writing a scene only to deliver information.", "Ending where the scene began.", "Using argument volume instead of tactical change.", "Cutting away before consequence."],
    exercise: "Complete the Dynamic Scene chain for the active scene. Rewrite the ending so its consequence launches the next mini-block.",
    apply: "Screenplay",
    tags: ["Dynamic Scenes", "objective", "opposition", "reversal", "turn", "consequence", "handoff"],
    howPlotPickleApplies: "Open the screenplay and use Dynamic Scene fields to test every scene’s movement and handoff.",
    visual: ["Objective", "Opposition", "Action", "Reversal", "Turn", "Consequence", "Handoff"],
  }),
];

export const twentyFourBlocksSourceMap = twentyFourBlocksLessons.map((item) => ({
  sourceConcept: item.sourceConcept,
  lessonId: item.id,
  title: item.title,
  workspace: item.workspaceLink,
  searchTerms: [item.sourceConcept, ...item.tags],
}));

export function twentyFourBlocksSearchText(module: TwentyFourBlocksLesson) {
  return [
    module.collection,
    module.sourceConcept,
    module.sourceNote,
    module.howPlotPickleApplies,
    ...module.visual,
  ].join(" ").toLowerCase();
}
