export function creativeWriterFixture() {
  const title = `Creative Writer UAT ${new Date().toISOString().slice(0, 10)}`;
  return {
    title,
    audience: "Adults who enjoy intimate speculative mysteries.",
    conceptSeed: "At dawn, a cartographer discovers that a drowned town is reappearing one street at a time.",
    emotionalPurpose: "Move from unease and grief toward wonder and deliberate hope.",
    audienceExperience: "A tactile mystery that becomes more personal with each visual discovery.",
    visualImpact: "Matte black water, amber practical light, silver fog, hand-drawn maps and wide negative space.",
    constraints: "Keep the protagonist human-led, the drowned town coastal, and every supernatural clue physically visible.",
    exploration: "Vary composition, weather, scale and visual metaphor without changing character identity or the central mystery.",
    ordinaryWorld: "A working harbour town rebuilding after repeated storms.",
    newWorld: "The exposed streets of the drowned settlement that appear only before sunrise.",
    visualLanguage: "Low-key dawn light, wet stone, amber lamps, weathered paper, restrained teal-grey atmosphere.",
    locationName: "The Drowned High Street",
    locationDescription: "A submerged commercial street exposed at low tide, lined with silt-covered windows and hanging signs.",
    characterName: "Mara Vale",
    characterRole: "Protagonist / cartographer",
    characterDescription: "A practical coastal cartographer in her forties, observant, dryly funny, carrying a weathered field case.",
    want: "Map the returning streets before the tide erases them.",
    need: "Accept that preserving a place is not the same as preserving the past.",
    blockTitle: "The Street Returns",
    blockSection: "Mara sees the first impossible street rise from the harbour mud.",
    goal: "Document the street before sunrise ends.",
    conflict: "The tide is returning and the town council orders the harbour closed.",
    choice: "Mara crosses the barrier alone.",
    action: "She follows old shop numbers into the exposed street.",
    consequence: "She finds her childhood home where no home should exist.",
    storyText: "Mara steps between drowned storefronts as water drains from the glass. A brass house number swings in the wind.",
    storyboardDirection: "Begin with a wide harbour reveal, move to Mara entering frame, isolate the swinging number, end on her recognition.",
    sceneHeading: "EXT. DROWNED HIGH STREET - DAWN",
    sceneAction: "Fog combs the exposed street. MARA VALE raises her field camera. The brass number ahead of her turns in the wind: 17.",
    feedbackTitle: "Clarify the visual recognition beat",
    feedbackBody: "The reveal is strong, but the audience should understand why the number 17 matters before the cut away.",
    proposedChange: "Hold on Mara's reaction, then insert the matching number from the map in her hand before returning to the house.",
  };
}
