export type StoryDecisionStatus = "new" | "reviewing" | "deferred" | "answered" | "superseded" | "stale" | "withdrawn";
export type StoryDecisionResponseClass = "accept-proposal" | "select-alternative" | "modify-proposal" | "reject-proposal" | "keep-current" | "request-alternatives" | "defer" | "freeform-decision";
export type StoryDecisionAuthorityClass = "authenticated-human" | "delegated-autonomous-operator";
export type StoryDecisionRecord = {
  readonly schemaVersion: 1;
  readonly decisionId: string;
  readonly problemKey: string;
  readonly groupKey: string;
  readonly projectId: string;
  readonly baseRevision: string;
  readonly origin: { readonly workItemId: string; readonly runIds: readonly string[]; readonly councilResultId: string; readonly contributionIds: readonly string[] };
  readonly decisionClass: string;
  readonly severity: "low" | "medium" | "high";
  readonly priority: number;
  readonly targetRefs: readonly string[];
  readonly curriculumRefs: readonly string[];
  readonly evidenceRefs: readonly string[];
  readonly question: string;
  readonly whyHuman: string;
  readonly proposedChange: string;
  readonly alternatives: readonly string[];
  readonly predictedImpactRefs: readonly string[];
  readonly visualContext: Readonly<Record<string, unknown>> | null;
  readonly status: StoryDecisionStatus;
  readonly createdAt: string;
  readonly updatedAt: string;
  readonly resolvedAt: string;
  readonly response: Readonly<Record<string, unknown>> | null;
  readonly provenance: { readonly source: string; readonly councilSummary: string; readonly humanGate: string; readonly transcriptRef: string };
  readonly integrity: { readonly writesCanon: false; readonly requiresWorkbenchValidation: true; readonly revisionAware: true };
  readonly history: readonly { readonly at: string; readonly event: string; readonly revision: string }[];
};
export declare const STORY_DECISION_VERSION: 1;
export declare const STORY_DECISION_STATUSES: readonly StoryDecisionStatus[];
export declare const STORY_DECISION_RESPONSE_CLASSES: readonly StoryDecisionResponseClass[];
export declare function storyDecisionEligible(councilResult: unknown, input?: { readonly blockedByHuman?: boolean }): boolean;
export declare function createStoryDecisionFromCouncilResult(input: Readonly<Record<string, unknown>>): StoryDecisionRecord | null;
export declare function normalizeStoryDecisionRecord(input: unknown): StoryDecisionRecord;
export declare function supersedeStoryDecision(input: unknown, replacementDecisionId?: string, now?: string): StoryDecisionRecord;
export declare function mergeStoryDecisionRecords(existingInput: unknown, incomingInput: unknown, input?: { readonly now?: string }): { readonly existing: StoryDecisionRecord; readonly incoming: StoryDecisionRecord | null; readonly merged: boolean };
export declare function markStoryDecisionStale(input: unknown, currentRevision: string, now?: string): StoryDecisionRecord;
export declare function withdrawStoryDecision(input: unknown, currentRevision?: string, now?: string): StoryDecisionRecord;
export declare function createStoryDecisionResponse(input: unknown, responseInput: Readonly<Record<string, unknown>>): { readonly decision: StoryDecisionRecord; readonly response: Readonly<Record<string, unknown>> };
export declare function rankStoryDecisions(input: readonly unknown[]): StoryDecisionRecord[];
export declare function storyDecisionAttentionCount(input: readonly unknown[]): number;
